# -*- coding: utf-8 -*-
"""Das Codebeispiel jeder Lektion, Zeile fuer Zeile erklaert.

Ein Beispiel, das man nur abtippt, lehrt nichts. Die Lektion sagt, WAS
gemacht wird; hier steht, was **jede einzelne Zeile** tut und warum sie
so und nicht anders dasteht -- einschliesslich der Zeilen, die man beim
Lesen ueberspringt, weil sie selbstverstaendlich aussehen.

lesson() haengt den passenden Eintrag selbst an, wie bei den
Herleitungen. Was hier fehlt, hat im Kurs keine Erklaerung.
"""
from __future__ import unicode_literals

CODEERKLAERUNGEN = {

"l-erstes":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`#include <stdio.h>` — holt die Beschreibung von `printf` herein. "
    "Ohne diese Zeile kennt der Übersetzer den Namen nicht und bricht ab. "
    "Die spitzen Klammern heißen: such in den Systemverzeichnissen; "
    "Anführungszeichen hießen: such zuerst neben dieser Datei.\n\n"
    "**Leerzeile** — reine Lesbarkeit. Der Übersetzer sieht sie nicht.\n\n"
    "`int main()` — hier fängt das Programm an. `int` ist der Typ dessen, "
    "was zurückgegeben wird; die leeren Klammern heißen „nimmt keine "
    "Argumente entgegen\". Der Name muss genau so lauten.\n\n"
    "`{` — öffnet den Rumpf. Alles bis zur passenden `}` gehört dazu.\n\n"
    "`    printf(\"Stroemung\\n\");` — schreibt den Text. Die "
    "Anführungszeichen begrenzen ihn, `\\n` ist **ein** Zeichen, nämlich "
    "der Zeilenumbruch; ohne ihn klebt die nächste Ausgabe daran. Der "
    "Strichpunkt beendet die Anweisung. Die vier Leerzeichen am "
    "Zeilenanfang sind Geschmack, kein Zwang — in Python wären sie "
    "Pflicht.\n\n"
    "`    return 0;` — beendet `main` und meldet der Umgebung: gut "
    "gegangen. Jede andere Zahl wäre eine Fehlernummer.\n\n"
    "`}` — schließt den Rumpf.\n\n"
    "**Warum kein Umlaut in „Stroemung\"?** Der Interpreter dieser App "
    "arbeitet zeichenweise in ASCII. Ein echter Übersetzer nähme das "
    "„ö\" ohne Weiteres.",

"l-variablen":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`int schritte = 100;` — legt einen Platz für eine ganze Zahl an, "
    "vier Byte, und schreibt 100 hinein. Das Anlegen und das Besetzen "
    "in einer Zeile ist kein Luxus: Eine Variable, die nur angelegt wird, "
    "enthält in C das, was zufällig im Speicher lag.\n\n"
    "`double dt = 0.01;` — dasselbe für eine Kommazahl, acht Byte. Der "
    "Punkt ist das Dezimaltrennzeichen, nie das Komma — `0,01` wäre etwas "
    "ganz anderes (zwei durch Komma getrennte Ausdrücke).\n\n"
    "`printf(\"%d Schritte zu je %.3f s\\n\", schritte, dt);` — die "
    "Zeichenkette ist eine **Vorlage**. Jeder Platzhalter darin zieht "
    "einen der nachfolgenden Werte an sich:\n\n"
    "* `%d` nimmt `schritte` und schreibt es als ganze Zahl,\n"
    "* `%.3f` nimmt `dt` und schreibt es mit drei Nachkommastellen.\n\n"
    "Die Reihenfolge entscheidet, nicht der Name. `printf` kennt die "
    "Typen der Werte nicht; es glaubt der Vorlage. Steht dort `%d`, wo "
    "ein `double` übergeben wird, liest es dieselben Bytes falsch und "
    "schreibt Unsinn — ohne Fehlermeldung.\n\n"
    "`printf(\"Gesamtzeit: %.2f s\\n\", schritte * dt);` — hier wird "
    "gerechnet, bevor ausgegeben wird. `schritte` ist ein `int`, `dt` ein "
    "`double`; C wandelt den `int` vorher um, weil **ein** Operand "
    "Fließkomma ist. Das Ergebnis ist 1.00, nicht 1 — und genau dieser "
    "Automatismus fehlt in der nächsten Lektion.",

"l-intdiv":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`int n = 4;` — eine ganze Zahl. Alles Weitere hängt daran, dass sie "
    "ganz ist.\n\n"
    "`printf(\"falsch: %f\\n\", 1 / n);` — **hier steckt die Falle.** "
    "Beide Operanden von `/` sind `int`: die `1` ist eine ganzzahlige "
    "Konstante, `n` ist ein `int`. Also rechnet C ganzzahlig: 1 geteilt "
    "durch 4 ist 0 Rest 1, und der Rest fällt weg. Das Ergebnis `0` wird "
    "dann als `%f` ausgegeben.\n\n"
    "Genau genommen ist das sogar doppelt falsch: `%f` erwartet ein "
    "`double`, bekommt aber einen `int`. Das ist undefiniertes "
    "Verhalten — der Interpreter dieser App zeigt `0.000000`, ein "
    "anderer Übersetzer dürfte irgendetwas zeigen.\n\n"
    "`printf(\"richtig: %f\\n\", 1.0 / n);` — ein einziges Zeichen "
    "Unterschied. `1.0` ist eine **Fließkommakonstante**; damit ist ein "
    "Operand `double`, C wandelt `n` vorher um, und die Division ist "
    "Fließkommadivision. Heraus kommt 0.25.\n\n"
    "**Die Regel daraus:** In einer Formel, deren Ergebnis Fließkomma "
    "sein soll, steht keine nackte ganze Zahl in einer Division. Also "
    "`1.0`, `2.0`, `0.5` schreiben — auch da, wo `1`, `2` und ein halbes "
    "Mal genügen würden.",

"l-if":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`double cfl = 0.7;` — die Courant-Zahl aus dem Kapitel zur "
    "Stabilität, hier als feste Zahl, damit man sie im Kopf verändern "
    "kann.\n\n"
    "`if (cfl <= 0.5) {` — die Bedingung steht in runden Klammern, und "
    "sie sind Pflicht. `<=` ist **ein** Operator; zwischen `<` und `=` "
    "darf kein Leerzeichen stehen. Die geschweifte Klammer öffnet den "
    "Zweig, der bei Zutreffen läuft.\n\n"
    "`    printf(\"stabil\\n\");` — läuft nur, wenn die Bedingung "
    "zutrifft. Hier nicht, denn 0,7 ist größer als 0,5.\n\n"
    "`} else {` — schließt den ersten Zweig und öffnet den anderen. "
    "`else` gehört immer zum nächststehenden offenen `if`; bei "
    "verschachtelten `if` ohne Klammern ist das die häufigste "
    "Verwechslung.\n\n"
    "`    printf(\"zu grosser Zeitschritt\\n\");` — dieser Zweig läuft.\n\n"
    "`}` — schließt.\n\n"
    "**Die Klammern sind hier freiwillig**, weil in jedem Zweig nur eine "
    "Anweisung steht. Trotzdem stehen sie da, und das ist Absicht: Wer "
    "später eine zweite Zeile hinzufügt und die Klammern vergisst, "
    "bekommt ein Programm, das etwas anderes tut, als es aussieht.\n\n"
    "**Und der Vergleich mit Fließkomma:** `<=` ist hier unbedenklich. "
    "Gefährlich wäre `==` — `if (cfl == 0.5)` träfe selbst dann nicht zu, "
    "wenn cfl das Ergebnis einer Rechnung wäre, die rechnerisch genau 0,5 "
    "ergibt.",

"l-for":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`double t = 0.0;` — die Zeit, bei null begonnen. Das ist der "
    "**Akkumulator**: die Größe, die die Schleife fortschreibt. Sie muss "
    "vor der Schleife stehen, sonst wäre sie nach jedem Durchlauf wieder "
    "weg.\n\n"
    "`double dt = 0.25;` — die Schrittweite. In einer echten Simulation "
    "käme sie aus der Stabilitätsbedingung.\n\n"
    "`int i;` — der Zähler, hier ohne Anfangswert, weil die Schleife ihn "
    "gleich setzt. (Moderne C-Fassungen erlauben `for (int i = 0; ...)`; "
    "der Interpreter dieser App mag die ältere Schreibweise lieber.)\n\n"
    "`for (i = 0; i < 4; i++) {` — drei Teile, durch Strichpunkte "
    "getrennt, und sie laufen zu **verschiedenen Zeiten**:\n\n"
    "* `i = 0` — einmal, ganz am Anfang;\n"
    "* `i < 4` — vor **jedem** Durchlauf, auch vor dem ersten;\n"
    "* `i++` — nach jedem Durchlauf.\n\n"
    "Daraus folgt: Der Rumpf läuft für i = 0, 1, 2, 3 — vier Mal. Und "
    "daraus folgt auch, dass er null Mal laufen kann, wenn die Bedingung "
    "schon beim ersten Prüfen nicht zutrifft.\n\n"
    "`    t = t + dt;` — der eigentliche Zeitschritt. Rechts steht der "
    "alte Wert, links wird der neue hineingeschrieben. Das ist keine "
    "Gleichung, sondern eine Zuweisung; als Gleichung gelesen wäre sie "
    "falsch.\n\n"
    "`    printf(\"Schritt %d, t = %.2f\\n\", i, t);` — zwei Platzhalter, "
    "zwei Werte, in dieser Reihenfolge.\n\n"
    "**Warum t am Ende 1.00 ist und nicht 0.75:** Erhöht wird **vor** der "
    "Ausgabe. Schritt 0 zeigt also schon t = 0,25. Wer die "
    "Anfangsbedingung mit ausgeben will, schreibt das `printf` vor die "
    "Erhöhung — ein Unterschied von einer Zeile, der in Auswertungen "
    "regelmäßig für einen Versatz um einen Zeitschritt sorgt.",

"l-euler":
    "## Das Beispiel Zeile für Zeile\n\n"
    "**Der Anfangszustand.** `x = 1.0` ist die Auslenkung, `v = 0.0` die "
    "Geschwindigkeit: Die Feder wird ganz ausgelenkt losgelassen. "
    "`dt = 0.05` ist der Zeitschritt, `t = 0.0` die Uhr.\n\n"
    "`double a, xn;` — zwei Hilfsgrößen ohne Anfangswert, weil die "
    "Schleife sie in jedem Durchlauf frisch berechnet. Mehrere Namen in "
    "einer Zeile sind erlaubt, solange der Typ derselbe ist.\n\n"
    "`for (i = 0; i < 400; i++) {` — 400 Schritte zu je 0,05 sind "
    "20 Sekunden simulierte Zeit. Die Feder schwingt mit einer "
    "Kreisfrequenz von 1, hat also eine Periode von 2π ≈ 6,28 — es sind "
    "gut drei Schwingungen.\n\n"
    "`a = -x;` — die Beschleunigung. Dahinter steckt das Newtonsche "
    "Gesetz `F = m·a` und das Hookesche `F = −k·x`. Mit m = 1 und k = 1 "
    "bleibt schlicht `a = −x`. Der Kommentar in der Zeile sagt genau "
    "das; `/* ... */` läuft über beliebig viele Zeilen und wird vom "
    "Übersetzer überlesen.\n\n"
    "`xn = x + v * dt;` — **hier ist der Kern der Lektion.** Der neue Ort "
    "wird in eine Hilfsvariable geschrieben, nicht in `x`. Der Grund "
    "steht im Kommentar: Beide Größen sollen aus den **alten** Werten "
    "fortgeschrieben werden. Schriebe man gleich in `x`, benutzte die "
    "nächste Zeile bereits den neuen Ort — und das wäre ein anderes "
    "Verfahren (nämlich das symplektische aus der Aufgabe).\n\n"
    "`v  = v + a * dt;` — die Geschwindigkeit, aus der alten "
    "Beschleunigung. `a` hängt nur von `x` ab, und `x` ist noch alt: "
    "deshalb darf diese Zeile vor der nächsten stehen.\n\n"
    "`x  = xn;` — jetzt erst wird der neue Ort übernommen.\n\n"
    "`t  = t + dt;` — die Uhr.\n\n"
    "`printf(\"plot %.3f %.5f\\n\", t, x);` — eine Zeile, die mit "
    "`plot` beginnt, zeichnet diese App als Kurve statt sie auszugeben. "
    "Danach kommen die x-Koordinate und die y-Koordinate. Fünf "
    "Nachkommastellen, weil die interessante Änderung in der vierten "
    "steckt.\n\n"
    "`printf(\"Energie am Ende: %.4f\\n\", 0.5*v*v + 0.5*x*x);` — die "
    "Gesamtenergie, kinetisch plus potentiell, mit m = k = 1. Am Anfang "
    "ist sie 0,5. Steht am Ende etwas Größeres da, hat das Verfahren "
    "Energie erzeugt — und genau darum geht es in dieser Lektion.",

"l-verlet":
    "## Das Beispiel Zeile für Zeile\n\n"
    "Bis auf drei Zeilen ist es dasselbe Programm wie beim "
    "Euler-Verfahren. Die drei sind der ganze Unterschied.\n\n"
    "`double a = -1.0;` — **neu:** Die Beschleunigung wird schon **vor** "
    "der Schleife berechnet, nicht in ihr. Verlet braucht sie am Anfang "
    "des Schritts, und am Ende jedes Schritts steht sie für den nächsten "
    "schon bereit. Mit `x = 1.0` ist `a = −x = −1.0`.\n\n"
    "`double an;` — Platz für die Beschleunigung am **Ende** des "
    "Schritts.\n\n"
    "`x = x + v * dt + 0.5 * a * dt * dt;` — der Ortsschritt, mit einem "
    "Glied mehr als bei Euler. Das `0.5 * a * dt * dt` ist genau das "
    "`dt²/2·x''` aus der Taylorreihe. Hier darf direkt in `x` "
    "geschrieben werden, weil der alte Ort danach nicht mehr gebraucht "
    "wird — `a` ist ja schon berechnet.\n\n"
    "`an = -x;` — die Beschleunigung am neuen Ort. **Das ist der eine "
    "zusätzliche Aufwand** gegenüber Euler: eine zweite Kraftauswertung "
    "je Schritt. Bei einer Feder kostet das nichts; bei einem "
    "N-Körper-Problem ist es der teuerste Teil überhaupt.\n\n"
    "`v = v + 0.5 * (a + an) * dt;` — **der entscheidende Griff.** Nicht "
    "die alte Beschleunigung und nicht die neue, sondern ihr Mittel. Das "
    "ist die Trapezregel, und sie hebt das Fehlerglied erster Ordnung "
    "auf.\n\n"
    "`a = an;` — die neue Beschleunigung wird zur alten für den nächsten "
    "Durchlauf. Ohne diese Zeile rechnete die Schleife ewig mit der "
    "Beschleunigung des ersten Schritts.\n\n"
    "`printf(\"plot verlet %.3f %.5f\\n\", t, x);` — hier steht ein "
    "**Name** zwischen `plot` und den Zahlen. Damit lassen sich mehrere "
    "Kurven in ein Bild zeichnen, jede mit eigener Farbe — nützlich, wenn "
    "man Euler und Verlet nebeneinanderlegt.\n\n"
    "**Worauf zu achten ist:** Die Energie am Ende. Bei Euler wuchs sie; "
    "hier sollte sie um 0,5 herum stehenbleiben.",

"l-funktionen":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`double kraft(double x, double k)` — eine Funktionsdefinition, und "
    "sie steht **vor** `main`. Das ist kein Stil, sondern nötig: Der "
    "Übersetzer liest von oben nach unten und muss den Namen kennen, "
    "bevor er den Aufruf sieht. (Die Alternative wäre eine Deklaration "
    "oben und die Definition unten.)\n\n"
    "Das erste `double` ist der **Rückgabetyp**, in den Klammern stehen "
    "die Parameter mit je eigenem Typ. `double x, k` in einer Klammer "
    "wäre ein Fehler — anders als bei Variablen muss jeder Parameter "
    "seinen Typ mitbringen.\n\n"
    "`return -k * x;` — rechnet und gibt zurück. `return` beendet die "
    "Funktion sofort; alles danach liefe nicht mehr.\n\n"
    "`double energie(double x, double v, double k)` — drei Parameter. "
    "Die Reihenfolge beim Aufruf muss zur Reihenfolge hier passen; die "
    "Namen sind innen frei wählbar und haben mit den Namen draußen "
    "nichts zu tun.\n\n"
    "`return 0.5 * v * v + 0.5 * k * x * x;` — Punkt vor Strich gilt auch "
    "hier, die Multiplikationen werden also zuerst gerechnet. `v * v` "
    "statt `pow(v, 2)`: schneller und ohne `math.h`.\n\n"
    "`printf(\"F = %.2f\\n\", kraft(x, k));` — der Aufruf steht "
    "dort, wo sonst ein Wert stünde. Erst wird `kraft` gerechnet, dann "
    "wird das Ergebnis an `printf` übergeben.\n\n"
    "**Was hier übergeben wird: Kopien.** `kraft` bekommt den Wert von "
    "`x`, nicht `x` selbst. Änderte die Funktion ihren Parameter, bliebe "
    "das draußen ohne Wirkung. Das ist in C immer so, ausnahmslos — wer "
    "eine Funktion braucht, die etwas verändert, übergibt einen Zeiger "
    "(Kapitel Felder und Zeiger) oder in C++ eine Referenz.",

"l-fliesskomma":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`#include <math.h>` — **neu**, wegen `fabs`. Auf einem echten "
    "System muss dafür beim Binden oft noch `-lm` dazu; der Interpreter "
    "dieser App bringt es mit.\n\n"
    "`double gross = 1e16;` — die Schreibweise `1e16` heißt 1 mal 10 hoch "
    "16. Der Wert ist mit Absicht so groß gewählt: Ein `double` hat rund "
    "16 Stellen, also ist die Eins ganz am Ende gerade noch "
    "darstellbar.\n\n"
    "`double klein = 1.0;`\n\n"
    "`double summe = gross + klein;` — **hier geschieht der Verlust.** Um "
    "die beiden Zahlen zu addieren, muss die kleinere auf den Exponenten "
    "der größeren gebracht werden. Dabei rutscht ihre Eins über das Ende "
    "der Mantisse hinaus und ist fort. `summe` ist damit exakt "
    "`gross`.\n\n"
    "`printf(\"verschwunden: %.1f\\n\", summe - gross);` — das "
    "beweist es: Herauskommt 0,0, obwohl eine Eins addiert wurde.\n\n"
    "`printf(\"ausgeloescht: %.1f\\n\", (1e8 + 1.0) - 1e8);` — "
    "derselbe Vorgang eine Größenordnung harmloser. Bei 1e8 passt die "
    "Eins noch, hier kommt also 1,0 heraus. Der Vergleich der beiden "
    "Zeilen zeigt, dass es keine feste Grenze gibt, sondern eine, die vom "
    "Verhältnis der Zahlen abhängt.\n\n"
    "`printf(\"nah genug?    %d\\n\", fabs(0.5 - 0.5) < 1e-9);` — so "
    "vergleicht man Fließkommazahlen: über den **Abstand**, nicht mit "
    "`==`. `fabs` ist der Betrag für Kommazahlen (`abs` wäre der für "
    "ganze Zahlen — eine beliebte Verwechslung, die still den "
    "Nachkommateil abschneidet). Der Vergleich liefert `1` oder `0`, "
    "deshalb `%d`.\n\n"
    "**Die Schranke 1e-9 ist nicht heilig.** Sie passt für Zahlen der "
    "Größenordnung eins. Wer Drücke in Pascal vergleicht, braucht eine "
    "andere — üblich ist eine **relative** Schranke: "
    "`fabs(a-b) <= 1e-9 * fabs(a)`.",

"l-felder":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`double summe(double *v, int n)` — der Parameter ist ein **Zeiger**, "
    "kein Feld. Das ist keine Nachlässigkeit: In C gibt es keine "
    "Möglichkeit, ein Feld an eine Funktion zu übergeben. Beim Aufruf "
    "zerfällt der Feldname zur Adresse seines ersten Elements, und genau "
    "die kommt an. Deshalb muss `n` mitgegeben werden — **die Länge "
    "steckt nicht im Zeiger.**\n\n"
    "`double s = 0.0;` — der Akkumulator, gesetzt. Uninitialisiert "
    "enthielte er Müll, und die Summe wäre bei jedem Start eine "
    "andere.\n\n"
    "`for (i = 0; i < n; i++) s += v[i];` — `s += v[i]` ist die Kurzform "
    "von `s = s + v[i]`. `v[i]` funktioniert am Zeiger genauso wie am "
    "Feld; es ist definiert als `*(v + i)`.\n\n"
    "`void verdoppeln(double *v, int n)` — `void` heißt: gibt nichts "
    "zurück. Die Funktion wirkt trotzdem nach außen, und **das ist der "
    "Punkt der Lektion**: Sie hat die Adresse bekommen, schreibt also in "
    "das Original.\n\n"
    "`for (i = 0; i < n; i++) v[i] = 2 * v[i];` — verdoppelt an Ort und "
    "Stelle.\n\n"
    "`double w[4];` — vier Plätze, Indizes 0 bis 3. Die Größe muss hier "
    "eine Konstante sein, weil das Feld auf dem Stapel liegt.\n\n"
    "`w[0] = 1.0; w[1] = 2.0; ...` — vier Anweisungen in einer Zeile sind "
    "erlaubt; der Strichpunkt trennt, nicht der Zeilenumbruch. In einem "
    "echten Programm stünde hier eine Schleife.\n\n"
    "`printf(\"%.1f\\n\", summe(w, 4));` — `w` allein ist die "
    "Adresse. Ein `&w` wäre nicht falsch, aber etwas anderes: die Adresse "
    "des ganzen Feldes statt die seines ersten Elements. Beide zeigen auf "
    "dieselbe Stelle, haben aber verschiedene Typen, und beim Rechnen "
    "damit fällt der Unterschied auf.\n\n"
    "`verdoppeln(w, 4);` — der Aufruf sieht aus wie der vorige, ändert "
    "aber das Feld. **Von außen ist das nicht zu sehen.** In C++ würde "
    "man `const double*` schreiben, um zu versprechen, dass nichts "
    "geändert wird; in C ist es ein Versprechen im Kommentar.\n\n"
    "`printf(\"%.1f\\n\", summe(w, 4));` — dieselbe Zeile wie oben, "
    "anderes Ergebnis: 10,0 und dann 20,0.",

"l-zeiger":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`void tauschen(double *a, double *b)` — zwei Zeiger. Mit "
    "`double a, double b` wäre die Funktion nutzlos: Sie tauschte ihre "
    "eigenen Kopien und ließe draußen alles, wie es war.\n\n"
    "`double t = *a;` — der **Stern liest**, worauf gezeigt wird. `t` ist "
    "danach eine gewöhnliche Kommazahl, eine Kopie des Werts.\n\n"
    "`*a = *b;` — hier steht der Stern **links**, und dann schreibt er. "
    "Links vom Gleichheitszeichen heißt `*a`: die Stelle, auf die `a` "
    "zeigt. Rechts heißt `*b`: der Wert, der dort steht.\n\n"
    "`*b = t;` — fertig getauscht.\n\n"
    "`double feld[3];` und `double *p;` — ein Feld und ein Zeiger. Sie "
    "sind **nicht** dasselbe: `feld` ist ein Platz für drei Zahlen, `p` "
    "ist ein Platz für eine Adresse.\n\n"
    "`p = feld;` — die Zuweisung geht ohne `&`, weil der Feldname schon "
    "die Adresse ist. Der Kommentar in der Zeile sagt genau das. `p = "
    "&feld[0]` wäre dasselbe, nur umständlicher.\n\n"
    "`tauschen(&x, &y);` — hier steht das `&`, denn `x` ist eine "
    "gewöhnliche Variable. Das `&` liefert ihre Adresse, und genau die "
    "erwartet die Funktion. Ohne `&` bekäme sie den Wert 1.0 als Adresse "
    "gedeutet — ein Absturz, wenn man Glück hat.\n\n"
    "`printf(\"%.1f %.1f\\n\", p[1], *(p + 1));` — **die Kernaussage "
    "der Lektion in einer Zeile.** Beide Ausdrücke liefern dasselbe, "
    "nämlich 20,0. `p[1]` ist per Definition `*(p + 1)`, und `p + 1` "
    "rückt nicht um ein Byte weiter, sondern um ein `double`, also um "
    "acht. Der Übersetzer weiß aus dem Typ, wie weit ein Schritt ist.\n\n"
    "**Daraus folgt auch:** `p + 3` bei einem Feld der Länge 3 zeigt "
    "hinter das Ende. Das ist noch erlaubt (und bei Schleifen üblich), "
    "aber `*(p + 3)` zu lesen ist es nicht.",

"l-stencil":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`int n = 41;` — 41 Gitterpunkte. Ungerade, damit `n/2` genau die "
    "Mitte trifft: 41/2 ist ganzzahlig 20, und das ist der 21. Punkt von "
    "41 — also die Mitte.\n\n"
    "`double r = 0.4;` — die Gitterzahl aus der Herleitung, unter der "
    "Stabilitätsgrenze von 0,5.\n\n"
    "`double u[41];` und `double w[41];` — **zwei** Felder. Das ist "
    "nicht Verschwendung, sondern Notwendigkeit, und der Grund steht "
    "unten.\n\n"
    "`for (i = 0; i < n; i++) u[i] = 0.0;` — alles auf null. In C ist ein "
    "Feld auf dem Stapel **nicht** genullt; ohne diese Schleife stünde "
    "dort, was zufällig im Speicher lag.\n\n"
    "`u[n / 2] = 1.0;` — ein Wärmepuls in der Mitte. Der Anfangszustand, "
    "dessen Auseinanderlaufen die Simulation zeigt.\n\n"
    "`for (i = 1; i < n - 1; i++)` — **die Schleife beginnt bei 1 und "
    "endet bei n−2**, nicht bei 0 und n−1. Der Grund ist der Stern "
    "selbst: Er greift auf `u[i-1]` und `u[i+1]` zu. Bei i = 0 wäre "
    "`u[-1]` ein Zugriff vor den Anfang des Feldes.\n\n"
    "`w[i] = u[i] + r * (u[i-1] - 2 * u[i] + u[i+1]);` — der "
    "Wärmeleitungsschritt, genau die Formel aus der Herleitung. Gelesen "
    "wird aus `u`, geschrieben nach `w`.\n\n"
    "**Und das ist der Grund für die zwei Felder.** Schriebe man direkt "
    "in `u`, benutzte der nächste Punkt links schon den **neuen** Wert "
    "und rechts noch den alten. Das Ergebnis hinge dann von der "
    "Laufrichtung der Schleife ab — und wäre ein anderes Verfahren "
    "(Gauß-Seidel statt Jacobi).\n\n"
    "`w[0] = 0.0;` und `w[n-1] = 0.0;` — die Randbedingung: An beiden "
    "Enden wird die Temperatur festgehalten. Physikalisch: zwei "
    "Wärmebäder. Deshalb nimmt die Summe über alle Zellen ab — Wärme "
    "fließt ab.\n\n"
    "`for (i = 0; i < n; i++) u[i] = w[i];` — zurückkopieren. In einem "
    "echten Löser tauscht man stattdessen zwei Zeiger; das kostet nichts, "
    "während dieses Kopieren bei einer Million Zellen je Zeitschritt "
    "spürbar wird.\n\n"
    "`printf(\"plot %d %.6f\\n\", i, u[i]);` — zeichnet das Profil. "
    "Die x-Achse ist hier der Index, nicht der Ort — bei gleichmäßigem "
    "Gitter derselbe Kurvenverlauf.\n\n"
    "`summe += u[i];` — die Summe als Probe. Ohne Abfluss müsste sie "
    "erhalten bleiben.",

"l-cfl":
    "## Das Beispiel Zeile für Zeile\n\n"
    "Es ist dasselbe Programm wie in der vorigen Lektion. Zwei Zahlen "
    "sind anders, und daran hängt alles.\n\n"
    "`double r = 0.6;` — **über** der hergeleiteten Grenze von 0,5. Der "
    "Kommentar sagt es. Das ist der einzige inhaltliche Unterschied.\n\n"
    "`int schritte = 60;` — weniger Schritte als vorher (200). Nicht aus "
    "Sparsamkeit: Bei r = 0,6 wächst der Fehler je Schritt um den Faktor "
    "|1 − 4r| = 1,4. Nach 200 Schritten wäre das 1,4 hoch 200 — eine Zahl "
    "mit 29 Nullen, die auch ein `double` nicht mehr trägt. Nach 60 "
    "Schritten sieht man die Explosion, ohne dass sie ins Unendliche "
    "läuft.\n\n"
    "`printf(\"plot %d %.3e\\n\", i, u[i]);` — **`%e` statt `%f`.** "
    "Die wissenschaftliche Schreibweise, also `1.234e+05`. Bei `%f` "
    "stünden dort nur Nullen oder unlesbar lange Ziffernketten; die "
    "Werte umspannen viele Größenordnungen.\n\n"
    "`if (u[i] > gross) gross = u[i];` — sucht den größten Wert. Ein "
    "`if` ohne geschweifte Klammern, weil nur eine Anweisung folgt — "
    "erlaubt, aber in der eigenen Arbeit besser mit Klammern.\n\n"
    "**Worauf zu achten ist, wenn man es laufen lässt:** nicht auf die "
    "Größe der Zahl, sondern auf ihr **Muster**. Benachbarte Punkte haben "
    "abwechselnd Plus und Minus. Das ist die Zickzack-Welle aus der "
    "von-Neumann-Rechnung — die kürzeste darstellbare Welle, die als "
    "erste explodiert. Eine Instabilität sieht nie aus wie ein zu großer "
    "Wert, sondern immer wie ein Sägezahn.\n\n"
    "**Zum Ausprobieren:** `r = 0.5` genau — dann steht das Verfahren an "
    "der Grenze und bleibt gerade noch stabil. `r = 0.51` genügt schon "
    "für die Explosion.",

"l-struct":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`struct Teilchen {` — die **Definition** des Typs. Sie legt keinen "
    "Speicher an; sie sagt nur, wie ein Teilchen aussieht.\n\n"
    "`    double x;` und `    double v;` — je ein Feld pro Zeile. Der "
    "Interpreter dieser App besteht darauf; ein echter Übersetzer nähme "
    "auch `double x, v;`.\n\n"
    "`};` — **der Strichpunkt nach der schließenden Klammer ist Pflicht.** "
    "Bei `if` und `for` steht dort keiner, hier schon, weil eine "
    "Strukturdefinition eine Deklaration ist. Ihn zu vergessen ist der "
    "häufigste Anfängerfehler mit Strukturen, und die Fehlermeldung "
    "zeigt meist auf die **nächste** Zeile.\n\n"
    "`double energie(struct Teilchen t)` — in C muss das Wort `struct` "
    "vor den Typnamen, jedes Mal. (`typedef` spart es; in C++ entfällt es "
    "von selbst.) Übergeben wird hier **eine Kopie** der ganzen Struktur, "
    "also 16 Byte. Bei einem Teilchen ist das gleichgültig; bei einer "
    "Struktur mit einem Gitter darin wäre es eine Katastrophe — dann "
    "nimmt man einen Zeiger.\n\n"
    "`return 0.5 * t.v * t.v + 0.5 * t.x * t.x;` — der **Punkt** greift "
    "auf ein Feld zu. Über einen Zeiger hieße es `t->v`.\n\n"
    "`struct Teilchen feld[4];` — vier Teilchen hintereinander im "
    "Speicher, zusammen 64 Byte. Das ist ein Feld von Strukturen "
    "(AoS).\n\n"
    "`feld[i].x = i * 0.5;` — erst der Index, dann der Punkt. Die "
    "Reihenfolge ist zwingend: `feld[i]` ist ein Teilchen, und davon wird "
    "das Feld `x` genommen. `i * 0.5` ist wieder eine gemischte Rechnung "
    "— `i` ist `int`, `0.5` ist `double`, also wird umgewandelt.\n\n"
    "`for (i = 0; i < 4; i++) gesamt += energie(feld[i]);` — bei jedem "
    "Durchlauf wird eine Struktur kopiert und übergeben.\n\n"
    "**Zum Nachdenken:** `sizeof(struct Teilchen)` ist hier 16 — zwei "
    "`double` ohne Lücke. Käme ein `int` dazu, wären es nicht 20, sondern "
    "24: Der Übersetzer füllt auf, damit das nächste `double` wieder auf "
    "einer durch acht teilbaren Adresse beginnt.",

"l-speicher":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`#include <stdlib.h>` — **neu**, für `malloc` und `free`. Ohne diese "
    "Zeile nimmt der Übersetzer an, `malloc` liefere ein `int`, und das "
    "geht auf einem 64-Bit-System schief.\n\n"
    "`int gesamt = nx * ny;` — die Zahl der Zellen, 48.\n\n"
    "`double *u = malloc(gesamt * sizeof(double));` — **die Kernzeile.** "
    "`malloc` nimmt eine Anzahl **Bytes**, nicht Elemente. Deshalb das "
    "`sizeof(double)`, hier 8; angefordert werden 384 Byte. Wer das "
    "`sizeof` vergisst, bekommt ein Achtel des nötigen Speichers und "
    "schreibt beim Rechnen darüber hinaus.\n\n"
    "Zurück kommt ein Zeiger auf den Anfang. `malloc` kann auch "
    "scheitern, dann liefert es `NULL` — in einem ernsthaften Programm "
    "stünde hier eine Prüfung.\n\n"
    "**Warum überhaupt `malloc`?** `double u[gesamt];` ginge nicht, weil "
    "`gesamt` keine Konstante ist, und der Stapel wäre bei einem echten "
    "Gitter ohnehin zu klein. Alles, was zur Laufzeit in seiner Größe "
    "feststeht, kommt auf den Haufen.\n\n"
    "`for (j = 0; j < ny; j++)` / `    for (i = 0; i < nx; i++)` — zwei "
    "geschachtelte Schleifen ohne Klammern, weil jede nur eine Anweisung "
    "umschließt. **Die Reihenfolge ist nicht beliebig:** j außen, i "
    "innen. So laufen die Zugriffe der Reihe nach durch den Speicher, und "
    "der Zwischenspeicher der CPU spielt mit. Vertauscht kostet dasselbe "
    "Programm ein Vielfaches.\n\n"
    "`u[j * nx + i] = i + j;` — **die flache Ablage.** Ein zweidimensio"
    "nales Gitter liegt eindimensional im Speicher; `j * nx + i` rechnet "
    "Zeile und Spalte in einen Index um. `nx` ist dabei die Zahl der "
    "**Spalten** — mit `ny` statt `nx` rechnet man still am falschen Ort, "
    "solange das Gitter nicht quadratisch ist.\n\n"
    "`u[2 * nx + 3]` — Zelle (i=3, j=2), also Spalte 3 in Zeile 2.\n\n"
    "`free(u);` — gibt den Speicher zurück. Ohne diese Zeile bleibt er "
    "belegt, bis das Programm endet; in einer Schleife, die immer wieder "
    "anfordert, ist das ein Leck. Nach `free` ist `u` **nicht** null, "
    "sondern zeigt auf Fremdes — deshalb setzt man ihn oft gleich danach "
    "auf `NULL`.",

"py-felder":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`import numpy as np` — `np` ist eine Abkürzung, aber eine "
    "verabredete: In der Numerik schreibt sie praktisch jeder so.\n\n"
    "`u = np.zeros(n)` — legt ein Feld aus 101 Nullen an. Anders als in C "
    "ist es hier tatsächlich genullt. Der Typ ist `float64`, also genau "
    "der `double` aus den C-Kapiteln.\n\n"
    "`u[n // 2] = 1.0` — **zwei Schrägstriche.** In Python 3 ist `/` "
    "immer Fließkommadivision; `101 / 2` wäre 50,5 und als Index "
    "unbrauchbar. `//` ist die ganzzahlige Division — genau das, was in C "
    "ein einfacher Schrägstrich tut. Die Ganzzahlfalle steht hier also "
    "andersherum.\n\n"
    "`u[1:-1] += r * (u[:-2] - 2*u[1:-1] + u[2:])` — **die ganze Lektion "
    "in einer Zeile.** Drei Ausschnitte desselben Feldes, je um eins "
    "gegeneinander verschoben:\n\n"
    "* `u[:-2]` — von Anfang bis zwei vor Ende: die linken Nachbarn,\n"
    "* `u[1:-1]` — die inneren Punkte selbst,\n"
    "* `u[2:]` — ab dem dritten: die rechten Nachbarn.\n\n"
    "Alle drei sind gleich lang (99 Werte), und die Rechnung läuft "
    "punktweise. Das ist dieselbe Formel wie in C, nur ohne Schleife — "
    "und die Ränder bleiben unberührt, weil `u[1:-1]` sie nicht "
    "einschließt.\n\n"
    "**Warum das schneller ist als eine Python-Schleife:** Die Schleife "
    "läuft in kompiliertem C innerhalb von NumPy. Eine Python-Schleife "
    "über 99 Punkte × 400 Schritte kostet 40 000 Durchläufe des "
    "Interpreters; hier sind es 400 Aufrufe in die Bibliothek.\n\n"
    "**Was die Zeile nicht ist:** an Ort und Stelle. `+=` auf einem "
    "Ausschnitt schreibt zwar in dasselbe Feld, aber die rechte Seite "
    "wird vollständig ausgerechnet, bevor zugewiesen wird. Genau deshalb "
    "braucht es hier kein zweites Feld wie in C — NumPy legt das "
    "Zwischenergebnis selbst an.\n\n"
    "`for i in range(0, n, 4):` — jeder vierte Punkt, damit die "
    "Zeichnung nicht aus 101 Punkten besteht. Der dritte Parameter von "
    "`range` ist die Schrittweite.",

"rs-erstes":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`fn main() {` — dieselbe Rolle wie `int main()` in C: hier fängt das "
    "Programm an. Kein `#include`, kein Rückgabetyp — `fn main()` ohne "
    "Pfeil gibt nichts zurück, und `println!` ist immer da.\n\n"
    "`let schritte = 100;` — `let` legt an. **Ohne Typ**: Rust schließt "
    "aus der `100`, dass es eine Ganzzahl ist, und aus dem späteren "
    "Gebrauch, welche (hier `i32`). Hinschreiben dürfte man ihn: "
    "`let schritte: i32 = 100;`.\n\n"
    "**Und ohne `mut` ist es unveränderlich.** `schritte = 101;` wäre ein "
    "Fehler beim Übersetzen. Das ist die Vorgabe, nicht die Ausnahme — "
    "umgekehrt wie in C.\n\n"
    "`let dt = 0.01;` — ein `f64`, dieselben acht Byte wie ein `double`.\n\n"
    "`println!(\"{} Schritte zu je {:.3} s\", schritte, dt);` — **das "
    "Ausrufezeichen gehört dazu.** Es kennzeichnet ein Makro, kein "
    "Funktionsaufruf. Der Unterschied ist kein Schönheitsfehler: Das "
    "Makro sieht die Vorlage beim Übersetzen und prüft, ob Zahl und Typen "
    "der Werte dazu passen. Ein `printf` mit falschem Platzhalter ist in "
    "C ein Laufzeitproblem; hier ist es gar kein Programm.\n\n"
    "Die Platzhalter heißen `{}` statt `%d` und `%f` — der Typ steht "
    "nicht drin, denn er ist bekannt. `{:.3}` sind drei "
    "Nachkommastellen.\n\n"
    "`println!(\"Gesamtzeit: {:.2} s\", schritte as f64 * dt);` — **das "
    "`as f64` ist Pflicht.** `schritte` ist eine Ganzzahl, `dt` eine "
    "Kommazahl, und Rust wandelt nicht von selbst um. In C liefe dieselbe "
    "Zeile ohne ein Wort — was in der nächsten Lektion zum Thema wird.\n\n"
    "**Kein `return 0;`** und kein Strichpunkt am Ende von `main`: Rust "
    "gibt den Erfolg selbst zurück.",

"rs-zahlen":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`let n = 4;` — eine Ganzzahl, Typ `i32`, aus der `4` geschlossen.\n\n"
    "`let h = 1.0 / n as f64;` — **die Zeile, um die es geht.** Ohne "
    "`as f64` wäre es kein Rundungsfehler wie in C, sondern gar kein "
    "Programm: `1.0` ist `f64`, `n` ist `i32`, und `/` gibt es für diese "
    "Mischung nicht. Der Übersetzer sagt das, und zwar mit dem Vorschlag, "
    "was zu tun ist.\n\n"
    "**Auf die Reihenfolge achten:** `as` bindet stärker als `/`, also "
    "wird erst `n` umgewandelt und dann geteilt. `(1.0 / n) as f64` wäre "
    "trotzdem ein Fehler, weil die Division selbst schon nicht "
    "übersetzt.\n\n"
    "`let ganz = 7 / 2;` — beide Operanden sind Ganzzahlen, also rechnet "
    "auch Rust ganzzahlig: 3. **Diese Hälfte der Falle gibt es hier "
    "genauso.** Was es nicht gibt, ist die stillschweigende Mischung.\n\n"
    "`println!(\"h = {:.3}\", h);` — 0.250.\n\n"
    "`println!(\"7 / 2 = {}\", ganz);` — 3. Ohne Nachkommastellen, denn "
    "es ist eine Ganzzahl; `{:.3}` wäre hier ein Übersetzungsfehler.\n\n"
    "`println!(\"7.0 / 2.0 = {}\", 7.0 / 2.0);` — 3.5. Zum Vergleich "
    "direkt darunter.\n\n"
    "**Der Punkt der drei Zeilen zusammen:** Die Ganzzahldivision ist "
    "nicht das Problem — sie ist in beiden Sprachen gleich und oft "
    "gewollt. Das Problem ist die stille Umwandlung daneben, und die "
    "fehlt hier.",

"l-upwind":
    "## Das Beispiel Zeile für Zeile\n\n"
    "Das Programm lässt **zwei Verfahren gleichzeitig** laufen, auf "
    "denselben Anfangsdaten, damit man sie im selben Bild vergleichen "
    "kann. Daher vier Felder statt zwei.\n\n"
    "`double C = 0.5;` — die Courant-Zahl, unter der Grenze von 1.\n\n"
    "`double a[41], b[41];` — altes und neues Feld für das "
    "**Aufwindverfahren**.\n\n"
    "`double z[41], y[41];` — dasselbe Paar für das **zentrale** "
    "Verfahren.\n\n"
    "`if (i >= n / 4 && i < n / 2) a[i] = 1.0;` — der Anfangszustand ist "
    "ein Rechteck: eins zwischen dem Viertel- und dem Halbpunkt, sonst "
    "null. Ein Rechteck ist mit Absicht gewählt — es hat scharfe Kanten, "
    "und an Kanten unterscheiden sich die beiden Verfahren am "
    "deutlichsten. `&&` ist das logische Und; beide Bedingungen müssen "
    "zutreffen.\n\n"
    "`z[i] = a[i];` — dasselbe Rechteck für das zweite Verfahren, damit "
    "der Vergleich fair ist.\n\n"
    "`b[i] = a[i] - C * (a[i] - a[i-1]);` — **das Aufwindverfahren.** Die "
    "Differenz wird nach **links** gebildet, also stromaufwärts, denn die "
    "Strömung kommt von dort. Genau das ist mit „Aufwind“ gemeint: Man "
    "schaut in die Richtung, aus der die Information kommt.\n\n"
    "`y[i] = z[i] - 0.5 * C * (z[i+1] - z[i-1]);` — **das zentrale "
    "Verfahren.** Die Differenz geht über beide Nachbarn, geteilt durch "
    "zwei (daher das `0.5`). Das ist genauer — zweiter Ordnung statt "
    "erster — und für reine Advektion trotzdem unbrauchbar: Es holt "
    "Information von rechts, wo physikalisch keine herkommt.\n\n"
    "`for (i = 0; i < n; i++) { a[i] = b[i]; z[i] = y[i]; }` — beide "
    "Paare zurückkopieren, in einer Schleife.\n\n"
    "`printf(\"plot aufwind %d %.5f\\n\", i, a[i]);` und `plot "
    "zentral ...` — zwei benannte Kurven in ein Bild.\n\n"
    "**Worauf zu achten ist:** Die Aufwindkurve ist **verschmiert** — die "
    "Kanten des Rechtecks sind weich geworden. Das ist die numerische "
    "Diffusion D_num = (v·h/2)(1−C) aus der Herleitung, und sie ist bei "
    "C = 0,5 am größten. Die zentrale Kurve hält die Kanten schärfer, hat "
    "dafür **Schwingungen** davor und dahinter, die physikalisch nicht da "
    "sein dürften. Man hat die Wahl zwischen unscharf und falsch — und "
    "genau deshalb gibt es die ganze Familie der Limiter-Verfahren.",

"rs-besitz-lektion":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`let gitter = vec![0.0; 5];` — `vec!` ist ein Makro (daher das "
    "Ausrufezeichen) und heißt hier: fünf Stück `0.0`. Das Ergebnis ist "
    "ein `Vec<f64>`, also ein Feld veränderlicher Länge auf dem Haufen — "
    "was in C++ `std::vector<double>` wäre.\n\n"
    "`let kopie = gitter.clone();` — **eine echte Kopie**, mit allem "
    "Inhalt. Sie kostet so viel wie das Feld groß ist, und genau deshalb "
    "muss man sie hinschreiben: In Rust gibt es keine teure Kopie, die "
    "aus Versehen geschieht.\n\n"
    "`let weitergegeben = gitter;` — **hier geschieht die Weitergabe.** "
    "Das sieht aus wie eine Zuweisung, ist aber keine Kopie: Der Besitz "
    "wandert von `gitter` zu `weitergegeben`. Danach ist `gitter` "
    "**ungültig** — nicht leer, nicht null, sondern nicht mehr benutzbar. "
    "Ein `println!(\"{}\", gitter.len());` an dieser Stelle wäre ein "
    "Fehler beim Übersetzen, mit der Meldung „value borrowed here after "
    "move“.\n\n"
    "`println!(\"weitergegeben: {} Zellen\", weitergegeben.len());` — "
    "der neue Besitzer darf.\n\n"
    "`println!(\"Kopie:         {} Zellen\", kopie.len());` — die Kopie "
    "war ja unabhängig.\n\n"
    "**Warum das überhaupt eine Regel ist.** Gäbe es zwei Namen für "
    "dasselbe Feld, müsste beim Aufräumen entschieden werden, wer den "
    "Speicher freigibt. Gäben beide frei, wäre es ein doppeltes `free` — "
    "einer der drei Fehler, die C-Programme nachts aufwecken. Rust "
    "verhindert ihn nicht durch Prüfen zur Laufzeit, sondern dadurch, "
    "dass es immer genau **einen** Besitzer gibt.\n\n"
    "**Und warum es nicht bei Zahlen gilt:** `let a = 5; let b = a;` "
    "lässt `a` gültig. Ein `i32` ist `Copy` — er passt in ein Register, "
    "und eine Kopie kostet nichts. Die Regel trifft nur, was Speicher "
    "besitzt.",

"rs-ausleihen":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`fn summe(v: &Vec<f64>) -> f64 {` — der Typ steht **hinter** dem "
    "Namen, durch Doppelpunkt getrennt, und der Rückgabetyp hinter einem "
    "Pfeil. In einer Signatur ist beides Pflicht, auch wenn Rust es "
    "innerhalb einer Funktion selbst schließt.\n\n"
    "**Das `&` ist das Ausleihen.** Die Funktion bekommt nicht den "
    "Besitz, sondern nur das Recht zu lesen. Ohne das `&` wäre `u` nach "
    "dem ersten Aufruf verbraucht, und der zweite ginge nicht mehr.\n\n"
    "`let mut s = 0.0;` — **`mut`**, weil sich `s` ändern soll. Ohne "
    "wäre `s = s + x;` ein Fehler.\n\n"
    "`for x in v {` — läuft über die Elemente, nicht über Indizes. `x` "
    "ist dabei selbst eine Ausleihe (`&f64`); Rust sieht beim Addieren "
    "hindurch.\n\n"
    "`    s` — **ohne Strichpunkt und ohne `return`.** Der letzte "
    "Ausdruck eines Blocks ist sein Wert. Ein Strichpunkt dahinter machte "
    "daraus eine Anweisung ohne Wert, und die Funktion gäbe nichts "
    "zurück — der Übersetzer meldete „expected f64, found ()“. Das ist "
    "einer der häufigsten Anfängerfehler in Rust.\n\n"
    "`fn skalieren(v: &mut Vec<f64>, f: f64) {` — **`&mut`**: eine "
    "Ausleihe, die schreiben darf. Davon gibt es zu jedem Zeitpunkt "
    "höchstens eine, und solange sie besteht, gibt es keine "
    "Leseausleihe.\n\n"
    "`for i in 0..v.len() {` — `0..n` ist der Bereich von 0 bis "
    "**ausschließlich** n; `0..=n` schlösse n ein. Über Indizes statt "
    "über Elemente, weil hier geschrieben wird.\n\n"
    "`let mut u = vec![1.0, 2.0, 3.0, 4.0];` — `mut`, weil `skalieren` "
    "gleich schreiben wird. Ohne `mut` ließe sich `&mut u` gar nicht "
    "bilden.\n\n"
    "`println!(\"vorher  {:.1}\", summe(&u));` — das `&` steht auch am "
    "**Aufrufort**. Anders als in C++ sieht man an der Aufrufstelle, ob "
    "übergeben oder ausgeliehen wird.\n\n"
    "`skalieren(&mut u, 2.5);` — und hier steht `&mut`, für jeden "
    "sichtbar, der die Zeile liest. Genau darum geht es: Dass eine "
    "Funktion ihr Argument verändert, ist keine Sache der Dokumentation, "
    "sondern steht im Quelltext.",

"rs-vec":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`fn schritt(u: &Vec<f64>, w: &mut Vec<f64>, r: f64) {` — **die "
    "Signatur ist die Dokumentation.** Aus dem alten Gitter wird nur "
    "gelesen (`&`), in das neue nur geschrieben (`&mut`). Wer die Zeile "
    "liest, weiß, was der Schritt tut, ohne den Rumpf anzusehen — und der "
    "Übersetzer hält es durch.\n\n"
    "`let n = u.len();` — **die Länge steckt im `Vec`**, anders als bei "
    "einem C-Zeiger. Deshalb braucht diese Funktion keinen Parameter "
    "dafür, und deshalb kann `w[i]` beim Zugriff prüfen, ob i im "
    "Bereich liegt.\n\n"
    "`for i in 1..n - 1 {` — von 1 bis n−2, genau wie in C und aus "
    "demselben Grund: Der Stern greift auf beide Nachbarn zu.\n\n"
    "`w[i] = u[i] + r * (u[i - 1] - 2.0 * u[i] + u[i + 1]);` — dieselbe "
    "Formel wie im C-Kapitel. **`2.0` und nicht `2`**, denn Rust mischt "
    "nicht.\n\n"
    "`let mut u = vec![0.0; n];` und `let mut w = vec![0.0; n];` — beide "
    "veränderlich, weil sie gleich getauscht werden.\n\n"
    "`for _schritt in 0..200 {` — **der Unterstrich** vor dem Namen sagt "
    "dem Übersetzer: Diese Variable wird absichtlich nicht benutzt. Ohne "
    "ihn käme eine Warnung.\n\n"
    "`schritt(&u, &mut w, r);` — Ausleihen am Aufrufort, wie in der "
    "Signatur.\n\n"
    "`std::mem::swap(&mut u, &mut w);` — **der Tausch, und er ist der "
    "Grund für dieses Beispiel.** In C wurde zurückkopiert; hier werden "
    "nur die drei Zahlen vertauscht, aus denen ein `Vec` besteht: Zeiger, "
    "Länge und Platz. Das kostet nichts, unabhängig von der Gittergröße. "
    "`u.clone()` an dieser Stelle kopierte das ganze Gitter je "
    "Zeitschritt — der übliche Anfängerfehler, und er ist hier "
    "sichtbar.\n\n"
    "Beide brauchen `&mut`, weil beide verändert werden. Zwei "
    "Schreibausleihen gleichzeitig sind sonst verboten — hier geht es, "
    "weil es zwei **verschiedene** Variablen sind.",

"rs-struct":
    "## Das Beispiel Zeile für Zeile\n\n"
    "`struct Teilchen {` / `    x: f64,` / `    v: f64,` / `}` — Name "
    "vor dem Doppelpunkt, Typ dahinter, **Komma** zwischen den Feldern "
    "und **kein Strichpunkt** hinter der schließenden Klammer. Genau "
    "umgekehrt zu C, wo der Strichpunkt Pflicht ist.\n\n"
    "`fn schritt(p: &mut Teilchen, dt: f64) {` — eine Schreibausleihe auf "
    "das Teilchen. Ohne `&` bekäme die Funktion den Besitz, und der "
    "Aufrufer hätte danach nichts mehr.\n\n"
    "`let a = -p.x;` — der Zugriff auf ein Feld geht mit dem **Punkt**, "
    "auch durch eine Ausleihe hindurch. Ein `->` wie in C gibt es nicht; "
    "Rust folgt dem Verweis von selbst.\n\n"
    "`p.v = p.v + a * dt;` und `p.x = p.x + p.v * dt;` — **Achtung, das "
    "ist nicht Euler.** Die Geschwindigkeit wird zuerst gerechnet, und "
    "der Ort benutzt dann schon die **neue** Geschwindigkeit. Das ist das "
    "symplektische Euler-Verfahren aus der Aufgabe zum Euler-Kapitel — "
    "zwei vertauschte Zeilen, und die Energie läuft nicht mehr davon.\n\n"
    "`fn energie(p: &Teilchen) -> f64 {` — nur eine Leseausleihe, denn "
    "hier wird nichts geändert. Der Unterschied zu `&mut` steht in der "
    "Signatur.\n\n"
    "`    0.5 * p.v * p.v + 0.5 * p.x * p.x` — wieder ohne Strichpunkt: "
    "der Wert des Blocks ist der Rückgabewert.\n\n"
    "`let mut p = Teilchen { x: 1.0, v: 0.0 };` — so wird eine Struktur "
    "angelegt: Name, geschweifte Klammern, jedes Feld mit seinem Wert. "
    "**Alle** Felder müssen dabei besetzt werden; ein halb gefülltes "
    "Teilchen gibt es nicht, und damit auch nicht den uninitialisierten "
    "Speicher aus dem C-Kapitel.\n\n"
    "`schritt(&mut p, 0.05);` — Ausleihe zum Schreiben, sichtbar an der "
    "Aufrufstelle.\n\n"
    "**Worauf zu achten ist:** Die Energie am Anfang und am Ende. Sie "
    "sollte nahezu gleich sein — mit denselben 400 Schritten und "
    "demselben dt, bei denen das gewöhnliche Euler-Verfahren im "
    "C-Kapitel um mehr als das Doppelte danebenlag.",

"l-projektion":
    "## Das Beispiel Zeile für Zeile\n\n"
    "Das ist das längste Programm des Kurses, aber es zerfällt in vier "
    "Abschnitte, die genau den vier Schritten der Herleitung "
    "entsprechen.\n\n"
    "**Die Felder.** `ux` und `uy` sind die beiden Komponenten der "
    "Geschwindigkeit, `d` ihre Divergenz, `p` das Druckpotential und `q` "
    "der Zwischenspeicher für den Löser. Fünf Gitter zu je 16×16 — hier "
    "als echte zweidimensionale Felder geschrieben, weil die Größe fest "
    "ist; ein richtiger Löser legt sie flach an wie im Kapitel "
    "Speicher.\n\n"
    "**Erster Abschnitt: der Anfangszustand.**\n\n"
    "`ux[j][i] = (i - n / 2.0) / n;` — ein Feld, das aus der Mitte nach "
    "außen zeigt, also eine **Quelle**. Solche Strömung kann es in einer "
    "inkompressiblen Flüssigkeit nicht geben, und genau das soll der "
    "Druckschritt beheben. Beachte `n / 2.0` mit dem Punkt: Mit `n / 2` "
    "wäre es Ganzzahldivision und die Mitte läge falsch.\n\n"
    "**Zweiter Abschnitt: die Divergenz messen.**\n\n"
    "`d[j][i] = 0.5 * (ux[j][i+1] - ux[j][i-1]) + 0.5 * (uy[j+1][i] - "
    "uy[j-1][i]);` — das ist ∇·u, mit der zentralen Ableitung in beiden "
    "Richtungen. Der Gitterabstand ist auf 1 gesetzt, deshalb steht nur "
    "das 0,5 der zentralen Differenz da.\n\n"
    "`w = d[j][i]; if (w < 0) w = -w; if (w > vorher) vorher = w;` — der "
    "Betrag von Hand, um `math.h` zu sparen, und daraus das Maximum. Das "
    "ist die Zahl, die nachher kleiner sein soll.\n\n"
    "**Dritter Abschnitt: die Poisson-Gleichung lösen.**\n\n"
    "`for (it = 0; it < 200; it++) {` — 200 Iterationen. Das ist kein "
    "Zeitschritt, sondern die Lösung eines Gleichungssystems durch "
    "Wiederholen.\n\n"
    "`q[j][i] = 0.25 * (p[j][i+1] + p[j][i-1] + p[j+1][i] + p[j-1][i] - "
    "d[j][i]);` — **das Jacobi-Verfahren.** Die Gleichung ∇²p = ∇·u "
    "lautet auf dem Gitter: p ist das Mittel seiner vier Nachbarn, minus "
    "der Divergenz. Nach `p` in der Mitte aufgelöst, ergibt sich genau "
    "diese Zeile. Man löst sie, indem man sie immer wieder anwendet — "
    "jede Runde trägt die Information einen Gitterpunkt weiter, und "
    "deshalb braucht man mindestens so viele Runden wie das Gitter breit "
    "ist.\n\n"
    "Geschrieben wird wieder in ein zweites Feld `q` und danach "
    "zurückkopiert, aus demselben Grund wie beim Wärmeleitungsschritt: "
    "Sonst hinge das Ergebnis von der Laufrichtung ab.\n\n"
    "**Vierter Abschnitt: den Gradienten abziehen.**\n\n"
    "`ux[j][i] -= 0.5 * (p[j][i+1] - p[j][i-1]);` — das ist `u = w − ∇φ` "
    "aus der Herleitung, Komponente für Komponente. `-=` zieht ab und "
    "schreibt zurück.\n\n"
    "**Die Probe.**\n\n"
    "`for (j = 2; j < n - 2; j++)` — die Schleife beginnt bei **2**, "
    "nicht bei 1. Das ist kein Tippfehler: Der Druckschritt hat nur die "
    "inneren Punkte verändert, also ist die Divergenz direkt am Rand "
    "nicht aussagekräftig. Gemessen wird dort, wo gerechnet wurde.\n\n"
    "`printf(\"Divergenz vorher %.6f nachher %.6f\\n\", vorher, "
    "nachher);` — **darauf kommt es an.** Vorher steht eine Zahl in der "
    "Größenordnung 0,1; nachher sollte sie um Größenordnungen kleiner "
    "sein. Nicht null: 200 Jacobi-Runden sind eine Näherung, und genau "
    "deshalb nimmt man in echten Lösern etwas Schnelleres.",

}
