# -*- coding: utf-8 -*-
"""Die Herleitung jeder Formel, die der Kurs benutzt.

Getrennt von curriculum.py, damit alle Formeln an einer Stelle zu
ueberblicken sind: Was hier nicht steht, hat keine Begruendung im Kurs.
lesson() haengt den passenden Eintrag selbst an den Lektionstext an.

Bei einem Simulationskurs ist das keine Kuer. Wer die Stabilitaetsgrenze
nur auswendig kennt, sucht bei einem anderen Verfahren im Dunkeln; wer die
von-Neumann-Rechnung einmal gesehen hat, stellt sie selbst auf.
"""
from __future__ import unicode_literals

HERLEITUNGEN = {

"l-euler":
    "## Herleitung: warum der Fehler mit `dt` fällt\n\n"
    "Die exakte Lösung lässt sich um den aktuellen Zeitpunkt entwickeln "
    "(Taylor):\n\n"
    "    x(t+dt) = x(t) + dt·x' + dt²/2·x'' + dt³/6·x''' + ...\n\n"
    "Das Euler-Verfahren nimmt davon genau die ersten zwei Glieder:\n\n"
    "    x_neu = x + dt·v\n\n"
    "Alles ab `dt²` wird weggelassen. Der Fehler **eines Schritts** ist "
    "also `dt²/2 · x''`, das heißt **O(dt²)**.\n\n"
    "Das klingt gut, ist aber nicht die Zahl, die zählt. Um bis zur Zeit "
    "`T` zu kommen, braucht man\n\n"
    "    N = T / dt      Schritte\n\n"
    "und die Fehler summieren sich. Grob gerechnet:\n\n"
    "    Gesamtfehler ≈ N · dt²/2 · x''\n"
    "                 = (T/dt) · dt²/2 · x''\n"
    "                 = T·dt/2 · x''\n\n"
    "Ein `dt` kürzt sich weg. Übrig bleibt **O(dt)** — deshalb heißt Euler "
    "ein Verfahren *erster* Ordnung, obwohl der einzelne Schritt zweiter "
    "Ordnung genau ist.\n\n"
    "**Die Probe:** Halbiert man `dt`, halbiert sich der Fehler. Genau das "
    "steht in der Tabelle oben. Bei einem Verfahren zweiter Ordnung würde "
    "er auf ein Viertel fallen.\n\n"
    "**Und warum die Energie wächst.** Beim harmonischen Oszillator ist "
    "E = ½(x² + v²). Ein Eulerschritt macht daraus\n\n"
    "    x_neu = x + dt·v,   v_neu = v − dt·x\n"
    "    E_neu = ½(x + dt·v)² + ½(v − dt·x)²\n"
    "          = ½(x² + v²)·(1 + dt²)\n"
    "          = E · (1 + dt²)\n\n"
    "Die gemischten Glieder heben sich auf, der Rest ist ein Faktor "
    "**immer größer als eins** — unabhängig von Vorzeichen und Lage. Das "
    "ist kein Rundungsfehler; kleineres `dt` macht es langsamer, nie "
    "besser. Euler pumpt systematisch Energie in ein abgeschlossenes "
    "System.",

"l-verlet":
    "## Herleitung: warum Verlet eine Ordnung besser ist\n\n"
    "**Der Ort.** Verlet nimmt aus der Taylorreihe ein Glied mehr mit:\n\n"
    "    x(t+dt) = x + dt·v + dt²/2·a + dt³/6·x''' + ...\n"
    "    x_neu   = x + dt·v + dt²/2·a\n\n"
    "Der Schrittfehler ist damit O(dt³) statt O(dt²). Über N = T/dt "
    "Schritte summiert bleibt **O(dt²)** — eine Ordnung besser als Euler. "
    "Halbes `dt` heißt hier ein Viertel Fehler, nicht die Hälfte.\n\n"
    "**Die Geschwindigkeit.** Der entscheidende Griff steckt nicht im "
    "Ortsschritt, sondern in\n\n"
    "    v_neu = v + dt/2 · (a_alt + a_neu)\n\n"
    "Das ist die Trapezregel, angewandt auf die Beschleunigung. Euler "
    "nimmt `a` am Anfang des Intervalls, das reine Rückwärtsverfahren am "
    "Ende. Beide liegen um `dt/2·a'` daneben, aber **mit verschiedenem "
    "Vorzeichen**. Der Mittelwert hebt genau dieses Glied auf:\n\n"
    "    ½[(a − dt/2·a') + (a + dt/2·a')] = a + O(dt²)\n\n"
    "**Warum die Energie nicht davonläuft.** Verlet ist *symplektisch*: "
    "Der Schritt erhält das Phasenraumvolumen exakt, nicht nur näherungs"
    "weise. Damit gibt es eine leicht veränderte Energie, die das "
    "Verfahren exakt erhält, und die echte Energie schwankt nur um diese "
    "herum — sie wächst nicht. Deshalb rechnet die Molekulardynamik seit "
    "Jahrzehnten mit Verlet und nicht mit etwas Genauerem: Nicht der "
    "Fehler nach einem Schritt zählt, sondern das Verhalten nach einer "
    "Milliarde.\n\n"
    "**Der Preis** ist eine einzige Zwischenspeicherung: `a_neu` muss "
    "berechnet sein, bevor `v` fertig ist. Eine Variable, eine Ordnung.",

"l-stencil":
    "## Herleitung: der Drei-Punkt-Stern und die Zahl `r`\n\n"
    "**Warum drei Punkte für die zweite Ableitung genügen.**\n\n"
    "Zwei Taylorentwicklungen, einmal nach rechts und einmal nach links:\n\n"
    "    u(x+h) = u + h·u' + h²/2·u'' + h³/6·u''' + h⁴/24·u'''' + ...\n"
    "    u(x−h) = u − h·u' + h²/2·u'' − h³/6·u''' + h⁴/24·u'''' − ...\n\n"
    "Addiert man beide, fallen **alle ungeraden Glieder** weg — die mit "
    "`u'` und `u'''` heben sich gegenseitig auf:\n\n"
    "    u(x+h) + u(x−h) = 2u + h²·u'' + h⁴/12·u''''\n\n"
    "Nach `u''` aufgelöst:\n\n"
    "    u'' = (u(x+h) − 2u(x) + u(x−h)) / h²  −  h²/12·u''''\n\n"
    "Der Fehler ist also **O(h²)**, obwohl nur drei Werte benutzt werden. "
    "Das ist das Geschenk der Symmetrie: Der Stern ist zweiter Ordnung "
    "genau, weil er genau so viel von links wie von rechts nimmt. Ein "
    "einseitiger Stern aus drei Punkten wäre nur erster Ordnung.\n\n"
    "**Und woher `r` kommt.** Die Wärmeleitungsgleichung lautet\n\n"
    "    ∂u/∂t = D · ∂²u/∂x²\n\n"
    "Diskretisiert mit Euler in der Zeit und dem Stern im Ort:\n\n"
    "    (u_neu − u_alt)/dt = D · (u₊ − 2u₀ + u₋)/h²\n\n"
    "Nach `u_neu` aufgelöst:\n\n"
    "    u_neu = u₀ + (D·dt/h²) · (u₊ − 2u₀ + u₋)\n\n"
    "Der Vorfaktor ist **eine einzige dimensionslose Zahl**:\n\n"
    "    r = D·dt/h²\n\n"
    "D hat die Einheit m²/s, dt ist s, h² ist m² — alles kürzt sich weg. "
    "Deshalb hängt das Verhalten des Verfahrens **nur an r** und nicht "
    "einzeln an D, dt oder h. Wer h halbiert, muss dt vierteln, um "
    "dasselbe r zu behalten. Das ist der eigentliche Preis eines feineren "
    "Gitters.",

"l-cfl":
    "## Herleitung: woher `r ≤ 1/2` kommt\n\n"
    "Die Grenze ist keine Erfahrung, sondern ausrechenbar. Das Verfahren "
    "ist linear, also darf man eine einzelne Welle hineinschicken und "
    "nachsehen, was mit ihr geschieht — die **von-Neumann-Analyse**:\n\n"
    "    u_j = g^n · e^(i·k·j·h)\n\n"
    "`g` ist der **Verstärkungsfaktor** je Zeitschritt. Ist |g| > 1 für "
    "irgendein k, wächst diese Welle unbegrenzt — und die Rundungsfehler "
    "liefern jede Wellenlänge frei Haus.\n\n"
    "Einsetzen in `u_neu = u₀ + r(u₊ − 2u₀ + u₋)` gibt\n\n"
    "    g = 1 + r·(e^(ikh) − 2 + e^(−ikh))\n\n"
    "Mit e^(ix) + e^(−ix) = 2cos(x) wird daraus\n\n"
    "    g = 1 + 2r·(cos(kh) − 1) = 1 − 4r·sin²(kh/2)\n\n"
    "Verlangt ist |g| ≤ 1 für **jedes** k. Nach oben ist nichts zu tun: "
    "sin² ≥ 0 macht g nur kleiner. Nach unten, im schlimmsten Fall "
    "sin²(kh/2) = 1 — das ist die kürzeste darstellbare Welle, die von "
    "Punkt zu Punkt springt:\n\n"
    "    1 − 4r ≥ −1      →      r ≤ 1/2\n\n"
    "Daher die Hälfte. Und daher auch, **wie** die Instabilität aussieht: "
    "Es ist immer die Zickzack-Welle, die zuerst explodiert, weil sie den "
    "größten Wert von sin² hat. Keine glatte Kurve, die davonläuft, "
    "sondern ein Sägezahn, der von Schritt zu Schritt das Vorzeichen "
    "wechselt und sich verdoppelt.\n\n"
    "## Und die CFL-Bedingung beim Transport\n\n"
    "Bei `∂u/∂t + v·∂u/∂x = 0` heißt die Zahl anders:\n\n"
    "    c = v·dt/h        (Courant-Zahl)\n\n"
    "Dieselbe Rechnung mit dem Aufwindschritt `u_neu = u₀ − c(u₀ − u₋)` "
    "liefert\n\n"
    "    |g|² = 1 − 2c(1−c)(1 − cos(kh))\n\n"
    "und das ist genau dann ≤ 1, wenn **0 ≤ c ≤ 1**.\n\n"
    "Anschaulich sagt dasselbe der Blick auf die Abhängigkeiten: In einem "
    "Zeitschritt läuft die Information physikalisch `v·dt` weit. Das "
    "Verfahren schaut aber nur einen Gitterpunkt weit, also `h`. Ist "
    "`v·dt > h`, kommt die Information von einem Punkt, den das Verfahren "
    "gar nicht befragt hat — es kann dann nicht richtig sein, "
    "gleichgültig wie fein man rechnet. Das ist die Aussage von Courant, "
    "Friedrichs und Lewy von 1928, und sie gilt für jedes explizite "
    "Verfahren.\n\n"
    "**Der Unterschied ist teuer.** Beim Transport skaliert dt mit h, bei "
    "der Wärmeleitung mit h². Halbes Gitter heißt dort doppelt so viele "
    "Schritte, hier viermal so viele.",

"l-funktionen":
    "## Herleitung: Trapezregel und warum Simpson so viel besser ist\n\n"
    "**Die Trapezregel.** Über einem Intervall der Breite h wird die "
    "Funktion durch die Gerade durch ihre beiden Endpunkte ersetzt. Die "
    "Fläche darunter ist\n\n"
    "    h · (f(a) + f(b)) / 2\n\n"
    "Wie weit daneben? Entwickelt man f um die Intervallmitte und "
    "integriert, bleibt\n\n"
    "    Fehler je Intervall = − h³/12 · f''(ξ)\n\n"
    "Die Gerade kann eine Krümmung nicht abbilden, deshalb steht dort "
    "`f''`. Über (b−a)/h Intervalle summiert:\n\n"
    "    Gesamtfehler = − (b−a)·h²/12 · f''      →      O(h²)\n\n"
    "Wieder fällt ein h weg, genau wie beim Euler-Verfahren. Zehn Trapeze "
    "über [0, π] geben deshalb rund ein Prozent Fehler; hundert geben ein "
    "Hundertstel davon.\n\n"
    "**Und die halben Randwerte** in der Summenformel sind kein Kniff, "
    "sondern fallen von selbst an: Jedes Trapez trägt seine beiden Ecken "
    "zur Hälfte bei, und jeder innere Punkt ist Ecke von **zwei** "
    "Trapezen — zwei halbe machen eins. Nur die beiden Ränder gehören zu "
    "je einem Trapez und bleiben halb.\n\n"
    "**Warum Simpson vierter Ordnung ist.** Simpson legt statt einer "
    "Geraden eine **Parabel** durch drei Punkte, mit den Gewichten "
    "1, 4, 2, 4, ..., 4, 1. Eine Parabel bildet die Krümmung exakt ab, "
    "also fällt das `f''`-Glied weg. Überraschend ist, dass auch das "
    "`f'''`-Glied verschwindet: Es ist ungerade, und die symmetrische "
    "Anordnung der drei Punkte hebt es auf — dieselbe Ersparnis wie beim "
    "Drei-Punkt-Stern. Übrig bleibt\n\n"
    "    Fehler = − (b−a)·h⁴/180 · f''''      →      O(h⁴)\n\n"
    "Simpson ist damit für Polynome bis zum **dritten** Grad exakt, "
    "obwohl es nur eine Parabel legt. Halbes h heißt ein Sechzehntel "
    "Fehler statt ein Viertel — bei gleicher Zahl von Funktionsaufrufen.",

"l-upwind":
    "## Herleitung: warum Aufwind verschmiert\n\n"
    "Das Aufwindverfahren ist stabil, aber es löst nicht ganz die "
    "Gleichung, die man hingeschrieben hat. Welche dann? Das verrät die "
    "**modifizierte Gleichung**: Man setzt die exakte Lösung in das "
    "diskrete Schema ein und entwickelt.\n\n"
    "Für `u_neu = u₀ − c(u₀ − u₋)` mit c = v·dt/h kommt heraus\n\n"
    "    ∂u/∂t + v·∂u/∂x = D_num · ∂²u/∂x²\n\n"
    "mit\n\n"
    "    D_num = (v·h/2)·(1 − c)\n\n"
    "Rechts steht ein Diffusionsterm, den niemand hingeschrieben hat. Das "
    "Verfahren transportiert also nicht nur — es **diffundiert zusätzlich**, "
    "und zwar umso mehr, je gröber das Gitter ist.\n\n"
    "Drei Folgerungen stehen direkt da.\n\n"
    "**Erstens:** Die Verschmierung ist proportional zu `h`. Feineres "
    "Gitter heißt schärfere Kante — aber nur linear, was teuer ist.\n\n"
    "**Zweitens:** Bei `c = 1` wird D_num genau **null**. Dann ist das "
    "Verfahren exakt: Die Information rückt in einem Zeitschritt um genau "
    "einen Gitterpunkt weiter, und das ist genau das, was geschehen soll. "
    "Dieser Sonderfall heißt *unit CFL*, und er ist der Grund, warum man "
    "beim Transport gern **nahe** an die Stabilitätsgrenze geht statt weit "
    "darunter — anders als bei der Wärmeleitung.\n\n"
    "**Drittens:** Das zentrale Verfahren hat kein solches Glied, deshalb "
    "verschmiert es nicht. Dafür ist sein Fehlerglied dispersiv statt "
    "diffusiv: Wellen verschiedener Länge laufen verschieden schnell, und "
    "hinter der Kante bleiben Schwingungen stehen. Man hat die Wahl "
    "zwischen einer unscharfen Kante und einer scharfen mit Kielwasser.",

"l-projektion":
    "## Herleitung: warum ein Druckschritt divergenzfrei macht\n\n"
    "Die Rechnung steht auf einem Satz aus der Vektoranalysis, der "
    "**Helmholtz-Hodge-Zerlegung**: Jedes hinreichend glatte Feld `w` "
    "lässt sich eindeutig zerlegen in\n\n"
    "    w = u + ∇φ\n\n"
    "wobei `u` divergenzfrei ist (∇·u = 0) und `∇φ` ein reines "
    "Gradientenfeld. Die beiden Anteile stehen im Funktionenraum senkrecht "
    "aufeinander — deshalb ist die Zerlegung eindeutig, und deshalb heißt "
    "der Schritt **Projektion**.\n\n"
    "Zu holen ist `u`. Bekannt ist `w`, das Geschwindigkeitsfeld nach dem "
    "Transportschritt, das die Divergenzfreiheit verletzt. Also die "
    "Divergenz auf beide Seiten anwenden:\n\n"
    "    ∇·w = ∇·u + ∇·∇φ = 0 + ∇²φ\n\n"
    "Das ist eine **Poisson-Gleichung** für φ:\n\n"
    "    ∇²φ = ∇·w\n\n"
    "Die löst man (hier mit Gauß-Seidel), und dann ist\n\n"
    "    u = w − ∇φ\n\n"
    "divergenzfrei — per Konstruktion, nicht näherungsweise.\n\n"
    "**Was φ physikalisch ist:** der Druck, bis auf einen Faktor. Das ist "
    "keine Analogie. In einer inkompressiblen Strömung ist der Druck keine "
    "eigene Zustandsgröße mit eigener Gleichung, sondern genau der "
    "Lagrange-Multiplikator, der die Bedingung ∇·u = 0 erzwingt. Deshalb "
    "gibt es keine Druckgleichung zu integrieren, und deshalb muss die "
    "Poisson-Gleichung in **jedem** Zeitschritt neu gelöst werden.\n\n"
    "**Und deshalb ist sie der teuerste Teil.** Der Transportschritt ist "
    "lokal: Jede Zelle schaut ihre Nachbarn an. Die Poisson-Gleichung ist "
    "global — eine Quelle in einer Ecke ändert den Druck im ganzen Gebiet, "
    "sofort. Das ist kein Mangel des Verfahrens, sondern die Physik der "
    "Inkompressibilität: Schall hat unendliche Geschwindigkeit, wenn man "
    "ihn wegdefiniert hat.",

}
