# -*- coding: utf-8 -*-
"""Die Herleitung jeder Formel, die der Kurs benutzt.

Getrennt von curriculum.py, damit alle Formeln an einer Stelle zu
ueberblicken sind: Was hier nicht steht, hat keine Begruendung im Kurs.
lesson() haengt den passenden Eintrag selbst an den Lektionstext an.

Drei Regeln fuer jeden Eintrag:

1. **Jedes Formelzeichen wird definiert**, mit Bedeutung und Einheit,
   bevor es in einer Formel auftaucht.
2. **Jede Formel wird hergeleitet** -- auch die, die erst in einer
   Herleitung auftaucht. Eine Begruendung, die ihrerseits eine
   unbegruendete Formel benutzt, hat nichts erklaert, sondern nur
   verschoben.
3. **Jede sagt, wo sie aufhoert zu gelten.** Wer die Stabilitaetsgrenze
   nur auswendig kennt, sucht bei einem anderen Verfahren im Dunkeln.
"""
from __future__ import unicode_literals

# Die Taylorentwicklung steht unter fast jeder Herleitung in diesem Kurs.
# Sie deshalb einmal ordentlich, und dann ueberall dieselbe.
TAYLOR = (
    "## Vorab: woher die Taylorreihe kommt\n\n"
    "**Zeichen hier:** `f` eine beliebige glatte Funktion. `x` die Stelle, "
    "um die entwickelt wird. `h` der Abstand davon. `f'`, `f''`, `f⁽ⁿ⁾` "
    "erste, zweite, n-te Ableitung. `n!` Fakultaet, also 1·2·...·n. "
    "`P` das gesuchte Polynom. `aₙ` seine Koeffizienten.\n\n"
    "Fast alles hier steht auf einer einzigen Idee: Eine glatte Funktion "
    "laesst sich in der Naehe eines Punktes durch ein Polynom ersetzen — "
    "und zwar durch genau eines.\n\n"
    "Gesucht ist das Polynom `P`, das an der Stelle `x` denselben Wert, "
    "dieselbe Steigung, dieselbe Kruemmung und so weiter hat wie `f`. "
    "Schreibt man es in Potenzen von `h`:\n\n"
    "    P(x+h) = a₀ + a₁·h + a₂·h² + a₃·h³ + ...\n\n"
    "dann liest man die Koeffizienten der Reihe nach ab. Bei `h = 0` "
    "bleibt nur `a₀`, also ist `a₀ = f(x)`. Einmal nach `h` abgeleitet und "
    "wieder `h = 0` gesetzt: `a₁ = f'(x)`. Zweimal abgeleitet gibt "
    "`2·a₂ = f''(x)`, dreimal `6·a₃ = f'''(x)`. Allgemein taucht beim "
    "n-ten Ableiten der Faktor n! auf:\n\n"
    "    aₙ = f⁽ⁿ⁾(x) / n!\n\n"
    "und damit\n\n"
    "    f(x+h) = f(x) + h·f'(x) + h²/2·f''(x) + h³/6·f'''(x) + ...\n\n"
    "**Warum das benutzbar ist:** Bricht man nach dem Glied mit `hⁿ` ab, "
    "ist der Rest von der Groesse `h⁽ⁿ⁺¹⁾` — er wird also schnell klein, "
    "wenn `h` klein wird. Genau das meint die Schreibweise **O(hⁿ⁺¹)**: "
    "„waechst hoechstens so schnell wie h hoch n+1\". Halbiert man `h`, "
    "faellt ein O(h)-Fehler auf die Haelfte, ein O(h²)-Fehler auf ein "
    "Viertel, ein O(h⁴)-Fehler auf ein Sechzehntel.\n\n"
    "**Wo es aufhoert:** Die Reihe braucht eine Funktion, die oft genug "
    "differenzierbar ist. An einem Knick oder Sprung gilt keine dieser "
    "Aussagen mehr — und genau deshalb verhalten sich numerische "
    "Verfahren an Stossfronten anders als im Lehrbuch.")


HERLEITUNGEN = {

"l-euler":
    "## Formelzeichen\n\n"
    "`x` — Ort, m. `v` — Geschwindigkeit, m/s. `a` — Beschleunigung, "
    "m/s². `t` — Zeit, s. `dt` — Zeitschritt, s. `T` — Gesamtzeit, s. "
    "`N` — Zahl der Schritte, dimensionslos. `E` — Energie, J. "
    "`m` — Masse, kg. `k` — Federkonstante, N/m. "
    "`O(·)` — Groessenordnung des Fehlers, siehe unten.\n\n"
    + TAYLOR + "\n\n"
    "## Herleitung: warum der Fehler mit `dt` faellt\n\n"
    "Die exakte Loesung, um den aktuellen Zeitpunkt entwickelt:\n\n"
    "    x(t+dt) = x(t) + dt·x' + dt²/2·x'' + dt³/6·x''' + ...\n\n"
    "Das Euler-Verfahren nimmt davon genau die ersten zwei Glieder:\n\n"
    "    x_neu = x + dt·v          (denn x' = v)\n\n"
    "Alles ab `dt²` wird weggelassen. Der Fehler **eines Schritts** ist "
    "also `dt²/2 · x''`, das heisst **O(dt²)**.\n\n"
    "Das klingt gut, ist aber nicht die Zahl, die zaehlt. Um bis zur Zeit "
    "`T` zu kommen, braucht man\n\n"
    "    N = T / dt      Schritte\n\n"
    "und die Fehler summieren sich. Grob gerechnet:\n\n"
    "    Gesamtfehler ≈ N · dt²/2 · x''\n"
    "                 = (T/dt) · dt²/2 · x''\n"
    "                 = T·dt/2 · x''\n\n"
    "Ein `dt` kuerzt sich weg. Uebrig bleibt **O(dt)** — deshalb heisst "
    "Euler ein Verfahren *erster* Ordnung, obwohl der einzelne Schritt "
    "zweiter Ordnung genau ist.\n\n"
    "**Die Probe:** Halbiert man `dt`, halbiert sich der Fehler. Genau "
    "das steht in der Tabelle oben. Bei einem Verfahren zweiter Ordnung "
    "wuerde er auf ein Viertel fallen.\n\n"
    "## Und woher `E = ½(x² + v²)` kommt\n\n"
    "Bevor gezeigt werden kann, dass die Energie waechst, muss klar sein, "
    "was sie ist. Ein Massepunkt an einer Feder hat\n\n"
    "    E = ½·m·v²  +  ½·k·x²\n\n"
    "Der erste Summand ist die Bewegungsenergie: Arbeit ist Kraft mal "
    "Weg, und integriert man `F = m·a` ueber den Weg, kommt ½mv² heraus. "
    "Der zweite ist die Spannenergie der Feder: Die Federkraft ist "
    "`F = −k·x` (Hooke), und das Integral von `k·x` ueber `x` ist ½kx².\n\n"
    "Im Beispiel sind Masse und Federkonstante beide auf 1 gesetzt — das "
    "ist keine Schlamperei, sondern Entdimensionalisierung: Man misst "
    "Zeit in Einheiten von √(m/k). Dann ist\n\n"
    "    a = −x      und      E = ½(x² + v²)\n\n"
    "## Und warum die Energie waechst\n\n"
    "Ein Eulerschritt macht daraus:\n\n"
    "    x_neu = x + dt·v,   v_neu = v − dt·x\n"
    "    E_neu = ½(x + dt·v)² + ½(v − dt·x)²\n\n"
    "Ausmultipliziert:\n\n"
    "    ½(x² + 2·dt·x·v + dt²v²) + ½(v² − 2·dt·x·v + dt²x²)\n\n"
    "Die gemischten Glieder `±dt·x·v` heben sich exakt auf. Uebrig "
    "bleibt\n\n"
    "    E_neu = ½(x² + v²)·(1 + dt²) = E · (1 + dt²)\n\n"
    "Der Faktor ist **immer groesser als eins** — unabhaengig von "
    "Vorzeichen und Lage. Das ist kein Rundungsfehler; kleineres `dt` "
    "macht es langsamer, nie besser. Euler pumpt systematisch Energie in "
    "ein abgeschlossenes System.",

"l-verlet":
    "## Formelzeichen\n\n"
    "`x` — Ort, m. `v` — Geschwindigkeit, m/s. `a` — Beschleunigung, "
    "m/s². `t` — Zeit, s. `dt` — Zeitschritt, s. `T` — Gesamtzeit, s. "
    "`N` — Zahl der Schritte. `a_alt`, `a_neu` — Beschleunigung am "
    "Anfang und am Ende des Schritts. `a'` — ihre Aenderung mit der "
    "Zeit.\n\n"
    "## Herleitung: warum Verlet eine Ordnung besser ist\n\n"
    "**Der Ort.** Verlet nimmt aus der Taylorreihe ein Glied mehr mit:\n\n"
    "    x(t+dt) = x + dt·v + dt²/2·a + dt³/6·x''' + ...\n"
    "    x_neu   = x + dt·v + dt²/2·a\n\n"
    "Der Schrittfehler ist damit O(dt³) statt O(dt²). Ueber N = T/dt "
    "Schritte summiert bleibt **O(dt²)** — eine Ordnung besser als Euler. "
    "Halbes `dt` heisst hier ein Viertel Fehler, nicht die Haelfte.\n\n"
    "**Die Geschwindigkeit.** Der entscheidende Griff steckt nicht im "
    "Ortsschritt, sondern in\n\n"
    "    v_neu = v + dt/2 · (a_alt + a_neu)\n\n"
    "Das ist die Trapezregel, angewandt auf die Beschleunigung. Warum sie "
    "hilft, sieht man durch Entwickeln. Die Beschleunigung am Ende des "
    "Schritts ist\n\n"
    "    a_neu = a + dt·a' + O(dt²)\n\n"
    "Euler nimmt `a` am Anfang und liegt damit um `dt/2·a'` zu tief; das "
    "reine Rueckwaertsverfahren nimmt `a_neu` und liegt um `dt/2·a'` zu "
    "hoch. **Mit verschiedenem Vorzeichen.** Der Mittelwert hebt genau "
    "dieses Glied auf:\n\n"
    "    ½(a + a_neu) = ½(a + a + dt·a') = a + dt/2·a'\n\n"
    "und das ist gerade die Beschleunigung in der **Mitte** des "
    "Intervalls, bis auf O(dt²). Deshalb ist der Schritt zentriert und "
    "damit zweiter Ordnung.\n\n"
    "## Warum die Energie nicht davonlaeuft\n\n"
    "Verlet ist *symplektisch*. Das heisst: Betrachtet man den Schritt "
    "als Abbildung des Paares (x, v) auf (x_neu, v_neu), so hat ihre "
    "Funktionaldeterminante exakt den Wert 1. Nachrechnen kann man das "
    "direkt — die Abbildung zerfaellt in zwei Scherungen, und eine "
    "Scherung aendert keine Flaeche.\n\n"
    "Ein Verfahren mit dieser Eigenschaft loest exakt ein leicht "
    "veraendertes Problem, das seinerseits eine Energie hat. Die echte "
    "Energie schwankt dann um diese herum — sie **waechst nicht**. "
    "Deshalb rechnet die Molekulardynamik seit Jahrzehnten mit Verlet und "
    "nicht mit etwas Genauerem: Nicht der Fehler nach einem Schritt "
    "zaehlt, sondern das Verhalten nach einer Milliarde.\n\n"
    "**Der Preis** ist eine einzige Zwischenspeicherung: `a_neu` muss "
    "berechnet sein, bevor `v` fertig ist. Eine Variable, eine Ordnung.",

"l-stencil":
    "## Formelzeichen\n\n"
    "`u` — die gesuchte Groesse, hier Temperatur, K. `x` — Ort, m. "
    "`t` — Zeit, s. `h` — Gitterabstand, m. `dt` — Zeitschritt, s. "
    "`D` — Diffusionskonstante, m²/s. `r` — die Gitter-Zahl `D·dt/h²`, "
    "dimensionslos. `u₊`, `u₀`, `u₋` — Werte am rechten Nachbarn, am "
    "Punkt selbst, am linken Nachbarn. `∂u/∂t` — Aenderung von `u` mit "
    "der Zeit bei festem Ort.\n\n"
    "## Herleitung: warum drei Punkte fuer die zweite Ableitung genuegen\n\n"
    "Zwei Taylorentwicklungen, einmal nach rechts und einmal nach "
    "links:\n\n"
    "    u(x+h) = u + h·u' + h²/2·u'' + h³/6·u''' + h⁴/24·u'''' + ...\n"
    "    u(x−h) = u − h·u' + h²/2·u'' − h³/6·u''' + h⁴/24·u'''' − ...\n\n"
    "Die zweite Zeile hat bei jeder **ungeraden** Potenz ein Minus, weil "
    "(−h)³ = −h³. Addiert man beide, heben sich genau diese Glieder "
    "auf:\n\n"
    "    u(x+h) + u(x−h) = 2u + h²·u'' + h⁴/12·u''''\n\n"
    "Nach `u''` aufgeloest:\n\n"
    "    u'' = (u(x+h) − 2u(x) + u(x−h)) / h²  −  h²/12·u''''\n\n"
    "Der Fehler ist also **O(h²)**, obwohl nur drei Werte benutzt werden. "
    "Das ist das Geschenk der Symmetrie: Der Stern ist zweiter Ordnung "
    "genau, weil er genau so viel von links wie von rechts nimmt. Ein "
    "einseitiger Stern aus drei Punkten waere nur erster Ordnung.\n\n"
    "## Und woher `r` kommt\n\n"
    "Die Waermeleitungsgleichung lautet\n\n"
    "    ∂u/∂t = D · ∂²u/∂x²\n\n"
    "In Worten: Ein Punkt erwaermt sich genau dann, wenn er kaelter ist "
    "als das Mittel seiner Nachbarn — und `∂²u/∂x²` misst genau diesen "
    "Abstand vom Nachbarmittel. Das ist keine Analogie, sondern das, was "
    "der Drei-Punkt-Stern oben ausrechnet: `(u₊ + u₋)/2 − u₀`, mal 2/h².\n\n"
    "Diskretisiert mit Euler in der Zeit und dem Stern im Ort:\n\n"
    "    (u_neu − u_alt)/dt = D · (u₊ − 2u₀ + u₋)/h²\n\n"
    "Nach `u_neu` aufgeloest:\n\n"
    "    u_neu = u₀ + (D·dt/h²) · (u₊ − 2u₀ + u₋)\n\n"
    "Der Vorfaktor ist **eine einzige dimensionslose Zahl**:\n\n"
    "    r = D·dt/h²\n\n"
    "Die Probe auf die Einheiten: D ist m²/s, dt ist s, h² ist m². "
    "Zaehler m²/s · s = m², Nenner m² — alles kuerzt sich weg, es bleibt "
    "eine reine Zahl.\n\n"
    "**Deshalb** haengt das Verhalten des Verfahrens nur an `r` und nicht "
    "einzeln an D, dt oder h. Wer h halbiert, muss dt vierteln, um "
    "dasselbe r zu behalten. Das ist der eigentliche Preis eines feineren "
    "Gitters.",

"l-cfl":
    "## Formelzeichen\n\n"
    "`u` — die transportierte Groesse. `h` — Gitterabstand, m. "
    "`dt` — Zeitschritt, s. `D` — Diffusionskonstante, m²/s. "
    "`v` — Transportgeschwindigkeit, m/s. `r = D·dt/h²` und "
    "`c = v·dt/h` — dimensionslos. `j` — Nummer des Gitterpunkts. "
    "`n` — Nummer des Zeitschritts. `k` — Wellenzahl, 1/m; die Welle hat "
    "die Laenge 2π/k. `g` — Verstaerkungsfaktor je Zeitschritt, "
    "dimensionslos. `i` — die imaginaere Einheit, i² = −1.\n\n"
    "## Vorab: warum man eine einzelne Welle hineinschicken darf\n\n"
    "Das Verfahren ist **linear**: Die Summe zweier Loesungen ist wieder "
    "eine Loesung. Jeder Anfangszustand laesst sich als Summe von "
    "Sinus- und Kosinuswellen schreiben (Fourier), und jede davon "
    "entwickelt sich unabhaengig von den anderen. Bleibt jede einzelne "
    "beschraenkt, bleibt die Summe es auch — und waechst **eine**, "
    "waechst am Ende alles, denn die Rundungsfehler liefern jede "
    "Wellenlaenge frei Haus.\n\n"
    "Gerechnet wird mit der komplexen Schreibweise `e^(ikx)` statt mit "
    "Sinus und Kosinus einzeln. Der Grund ist die **Eulersche Formel**\n\n"
    "    e^(ix) = cos(x) + i·sin(x)\n\n"
    "die man erhaelt, wenn man die Taylorreihen von e, cos und sin "
    "nebeneinanderlegt: Die Reihe von e^(ix) zerfaellt in einen reellen "
    "Teil, der genau die Kosinusreihe ist, und einen imaginaeren, der die "
    "Sinusreihe ist. Der Nutzen: Ableiten und Verschieben werden zu "
    "Multiplikationen. Aus ihr folgt sofort\n\n"
    "    e^(ix) + e^(−ix) = 2·cos(x)\n\n"
    "denn cos ist gerade und sin ungerade, die Sinusanteile heben sich "
    "auf.\n\n"
    "## Herleitung: woher `r ≤ 1/2` kommt\n\n"
    "Angesetzt wird eine einzelne Welle, die je Zeitschritt mit einem "
    "Faktor `g` multipliziert wird (**von-Neumann-Analyse**):\n\n"
    "    u_j = g^n · e^(i·k·j·h)\n\n"
    "Ist |g| > 1 fuer irgendein k, waechst diese Welle unbegrenzt.\n\n"
    "Einsetzen in `u_neu = u₀ + r(u₊ − 2u₀ + u₋)`. Der Nachbar rechts "
    "unterscheidet sich nur um den Faktor `e^(ikh)`, der linke um "
    "`e^(−ikh)`; alles andere kuerzt sich:\n\n"
    "    g = 1 + r·(e^(ikh) − 2 + e^(−ikh))\n\n"
    "Mit `e^(ix) + e^(−ix) = 2cos(x)` wird daraus\n\n"
    "    g = 1 + 2r·(cos(kh) − 1)\n\n"
    "Und mit der Halbwinkelformel `1 − cos(α) = 2·sin²(α/2)` — die aus "
    "`cos(2β) = 1 − 2sin²(β)` mit β = α/2 folgt —\n\n"
    "    g = 1 − 4r·sin²(kh/2)\n\n"
    "Verlangt ist |g| ≤ 1 fuer **jedes** k. Nach oben ist nichts zu tun: "
    "sin² ≥ 0 macht g nur kleiner. Nach unten, im schlimmsten Fall "
    "sin²(kh/2) = 1 — das ist die kuerzeste darstellbare Welle, die von "
    "Punkt zu Punkt springt:\n\n"
    "    1 − 4r ≥ −1      →      r ≤ 1/2\n\n"
    "Daher die Haelfte. Und daher auch, **wie** die Instabilitaet "
    "aussieht: Es ist immer die Zickzack-Welle, die zuerst explodiert, "
    "weil sie den groessten Wert von sin² hat. Keine glatte Kurve, die "
    "davonlaeuft, sondern ein Saegezahn, der von Schritt zu Schritt das "
    "Vorzeichen wechselt und sich verdoppelt.\n\n"
    "## Und die CFL-Bedingung beim Transport\n\n"
    "Bei `∂u/∂t + v·∂u/∂x = 0` heisst die Zahl anders:\n\n"
    "    c = v·dt/h        (Courant-Zahl)\n\n"
    "Dieselbe Rechnung mit dem Aufwindschritt `u_neu = u₀ − c(u₀ − u₋)` "
    "gibt\n\n"
    "    g = 1 − c + c·e^(−ikh)\n\n"
    "Das ist eine komplexe Zahl; ihr Betragsquadrat ist Realteil² plus "
    "Imaginaerteil²:\n\n"
    "    |g|² = (1 − c + c·cos(kh))² + (c·sin(kh))²\n"
    "         = 1 − 2c(1−c)(1 − cos(kh))\n\n"
    "wobei sin² + cos² = 1 benutzt wurde. Der Klammerausdruck "
    "`1 − cos(kh)` ist nie negativ, also ist |g|² genau dann ≤ 1, wenn "
    "`c(1−c) ≥ 0` — und das heisst **0 ≤ c ≤ 1**.\n\n"
    "Anschaulich sagt dasselbe der Blick auf die Abhaengigkeiten: In "
    "einem Zeitschritt laeuft die Information physikalisch `v·dt` weit. "
    "Das Verfahren schaut aber nur einen Gitterpunkt weit, also `h`. Ist "
    "`v·dt > h`, kommt die Information von einem Punkt, den das Verfahren "
    "gar nicht befragt hat — es kann dann nicht richtig sein, "
    "gleichgueltig wie fein man rechnet. Das ist die Aussage von Courant, "
    "Friedrichs und Lewy von 1928, und sie gilt fuer jedes explizite "
    "Verfahren.\n\n"
    "**Der Unterschied ist teuer.** Beim Transport skaliert dt mit h, bei "
    "der Waermeleitung mit h². Halbes Gitter heisst dort doppelt so viele "
    "Schritte, hier viermal so viele.",

"l-funktionen":
    "## Formelzeichen\n\n"
    "`f` — die zu integrierende Funktion. `a`, `b` — Untergrenze und "
    "Obergrenze. `h` — Breite eines Teilintervalls. `n` — Zahl der "
    "Teilintervalle, `h = (b−a)/n`. `ξ` — eine nicht naeher bekannte "
    "Stelle im Intervall (aus dem Mittelwertsatz). `f''`, `f''''` — "
    "zweite und vierte Ableitung.\n\n"
    "## Herleitung: die Trapezregel und ihr Fehler\n\n"
    "Ueber einem Intervall der Breite h wird `f` durch die Gerade durch "
    "ihre beiden Endpunkte ersetzt. Die Flaeche unter einer Gerade ist "
    "die eines Trapezes, also mittlere Hoehe mal Breite:\n\n"
    "    h · (f(a) + f(b)) / 2\n\n"
    "Wie weit daneben? Der Abstand zwischen `f` und ihrer Sekante ist "
    "bekannt: Fuer die lineare Interpolation gilt\n\n"
    "    f(x) − Gerade(x) = ½·f''(ξ)·(x−a)(x−b)\n\n"
    "Das Produkt `(x−a)(x−b)` ist im ganzen Intervall negativ; sein "
    "Integral ueber [a,b] ist `−h³/6`. Damit ist der Fehler\n\n"
    "    ½·f''·(−h³/6) = − h³/12 · f''(ξ)\n\n"
    "Die Gerade kann eine Kruemmung nicht abbilden — deshalb steht dort "
    "`f''`. Ueber n = (b−a)/h Intervalle summiert:\n\n"
    "    Gesamtfehler = n · (−h³/12·f'') = − (b−a)·h²/12 · f''\n\n"
    "also **O(h²)**. Wieder faellt ein h weg, genau wie beim "
    "Euler-Verfahren, und aus demselben Grund: Man addiert immer mehr "
    "immer kleinere Fehler.\n\n"
    "**Und die halben Randwerte** in der Summenformel sind kein Kniff, "
    "sondern fallen von selbst an: Jedes Trapez traegt seine beiden Ecken "
    "zur Haelfte bei, und jeder innere Punkt ist Ecke von **zwei** "
    "Trapezen — zwei halbe machen eins. Nur die beiden Raender gehoeren "
    "zu je einem Trapez und bleiben halb.\n\n"
    "## Warum Simpson vierter Ordnung ist\n\n"
    "Simpson legt statt einer Geraden eine **Parabel** durch drei Punkte. "
    "Integriert man die Parabel durch (x₀, x₁, x₂) mit Abstand h, kommt "
    "heraus\n\n"
    "    h/3 · (f₀ + 4f₁ + f₂)\n\n"
    "— daher die Gewichte 1, 4, 2, 4, ..., 4, 1 in der Summenformel: Die "
    "inneren Punkte mit geradem Index gehoeren zu zwei Parabeln und "
    "zaehlen deshalb doppelt.\n\n"
    "Eine Parabel bildet die Kruemmung exakt ab, also faellt das "
    "`f''`-Glied weg. Ueberraschend ist, dass auch das `f'''`-Glied "
    "verschwindet: Es ist ungerade, und die drei Punkte liegen "
    "symmetrisch um die Mitte — dieselbe Ersparnis wie beim "
    "Drei-Punkt-Stern. Uebrig bleibt\n\n"
    "    Fehler = − (b−a)·h⁴/180 · f''''      →      O(h⁴)\n\n"
    "Simpson ist damit fuer Polynome bis zum **dritten** Grad exakt, "
    "obwohl es nur eine Parabel legt. Halbes h heisst ein Sechzehntel "
    "Fehler statt ein Viertel — bei gleicher Zahl von Funktionsaufrufen.",

"l-upwind":
    "## Formelzeichen\n\n"
    "`u` — die transportierte Groesse. `v` — Transportgeschwindigkeit, "
    "m/s. `h` — Gitterabstand, m. `dt` — Zeitschritt, s. "
    "`c = v·dt/h` — Courant-Zahl, dimensionslos. `D_num` — die "
    "Diffusion, die das Verfahren selbst erzeugt, m²/s.\n\n"
    "## Herleitung: warum Aufwind verschmiert\n\n"
    "Das Aufwindverfahren ist stabil, aber es loest nicht ganz die "
    "Gleichung, die man hingeschrieben hat. Welche dann? Das verraet die "
    "**modifizierte Gleichung**, und die bekommt man so:\n\n"
    "Man setzt die **exakte** Loesung in das **diskrete** Schema ein und "
    "entwickelt alles in Taylorreihen. Was uebrigbleibt, ist die "
    "Gleichung, die das Schema wirklich loest.\n\n"
    "Fuer `u_neu = u₀ − c(u₀ − u₋)`, also\n\n"
    "    (u_neu − u₀)/dt + v·(u₀ − u₋)/h = 0\n\n"
    "wird der Zeitterm zu `u_t + dt/2·u_tt` und der Ortsterm zu "
    "`v·(u_x − h/2·u_xx)`. Zusammen:\n\n"
    "    u_t + v·u_x = − dt/2·u_tt + v·h/2·u_xx\n\n"
    "Aus der Gleichung selbst folgt `u_tt = v²·u_xx` (zweimal ableiten "
    "und einsetzen). Damit\n\n"
    "    u_t + v·u_x = (v·h/2 − v²·dt/2)·u_xx = (v·h/2)·(1 − c)·u_xx\n\n"
    "also\n\n"
    "    D_num = (v·h/2)·(1 − c)\n\n"
    "Rechts steht ein Diffusionsterm, den niemand hingeschrieben hat. Das "
    "Verfahren transportiert also nicht nur — es **diffundiert "
    "zusaetzlich**, und zwar umso mehr, je groeber das Gitter ist.\n\n"
    "Drei Folgerungen stehen direkt da.\n\n"
    "**Erstens:** Die Verschmierung ist proportional zu `h`. Feineres "
    "Gitter heisst schaerfere Kante — aber nur linear, was teuer ist.\n\n"
    "**Zweitens:** Bei `c = 1` wird D_num genau **null**. Dann ist das "
    "Verfahren exakt: Die Information rueckt in einem Zeitschritt um "
    "genau einen Gitterpunkt weiter, und das ist genau das, was geschehen "
    "soll. Dieser Sonderfall heisst *unit CFL*, und er ist der Grund, "
    "warum man beim Transport gern **nahe** an die Stabilitaetsgrenze "
    "geht statt weit darunter — anders als bei der Waermeleitung.\n\n"
    "**Drittens:** Das zentrale Verfahren hat kein solches Glied, deshalb "
    "verschmiert es nicht. Dafuer ist sein fuehrender Fehler ungerade "
    "(`u_xxx`) statt gerade, und das wirkt dispersiv statt diffusiv: "
    "Wellen verschiedener Laenge laufen verschieden schnell, und hinter "
    "der Kante bleiben Schwingungen stehen. Man hat die Wahl zwischen "
    "einer unscharfen Kante und einer scharfen mit Kielwasser.",

"l-projektion":
    "## Formelzeichen\n\n"
    "`u` — Geschwindigkeitsfeld, divergenzfrei, m/s. `w` — das Feld nach "
    "dem Transportschritt, noch nicht divergenzfrei, m/s. `φ` — das "
    "Potential, aus dem der Druck folgt. `∇` — der Nabla-Operator: auf "
    "ein Skalarfeld angewandt gibt er den Gradienten (Vektor der "
    "Ableitungen), auf ein Vektorfeld per Skalarprodukt die **Divergenz** "
    "`∇·u = ∂u_x/∂x + ∂u_y/∂y`. `∇²` — der Laplace-Operator, "
    "`∇²φ = ∇·∇φ = ∂²φ/∂x² + ∂²φ/∂y²`.\n\n"
    "**Was Divergenz bedeutet:** Sie misst, wie viel aus einem kleinen "
    "Kaestchen mehr herausfliesst als hinein. Ist sie null, bleibt so "
    "viel drin wie vorher — genau das heisst inkompressibel.\n\n"
    "## Herleitung: warum ein Druckschritt divergenzfrei macht\n\n"
    "Die Rechnung steht auf einem Satz aus der Vektoranalysis, der "
    "**Helmholtz-Hodge-Zerlegung**: Jedes hinreichend glatte Feld `w` "
    "laesst sich zerlegen in\n\n"
    "    w = u + ∇φ\n\n"
    "wobei `u` divergenzfrei ist und `∇φ` ein reines Gradientenfeld.\n\n"
    "**Warum eindeutig?** Weil die beiden Anteile aufeinander senkrecht "
    "stehen. Das Skalarprodukt zweier Felder ist das Integral ihres "
    "punktweisen Produkts, und fuer divergenzfreies `u` gilt\n\n"
    "    ∫ u · ∇φ = − ∫ φ · (∇·u) = 0\n\n"
    "(partielle Integration; der Randterm faellt bei passenden "
    "Randbedingungen weg). Zwei zueinander senkrechte Raeume koennen sich "
    "nur in der Null schneiden — also gibt es genau eine Zerlegung, und "
    "`u` herauszuholen heisst, senkrecht auf den divergenzfreien Raum zu "
    "**projizieren**. Daher der Name.\n\n"
    "Zu holen ist `u`. Bekannt ist `w`. Also die Divergenz auf beide "
    "Seiten anwenden:\n\n"
    "    ∇·w = ∇·u + ∇·∇φ = 0 + ∇²φ\n\n"
    "Das ist eine **Poisson-Gleichung** fuer φ:\n\n"
    "    ∇²φ = ∇·w\n\n"
    "Die loest man (hier mit Gauss-Seidel), und dann ist\n\n"
    "    u = w − ∇φ\n\n"
    "divergenzfrei — per Konstruktion, nicht naeherungsweise.\n\n"
    "**Was φ physikalisch ist:** der Druck, bis auf einen Faktor. Das ist "
    "keine Analogie. In einer inkompressiblen Stroemung ist der Druck "
    "keine eigene Zustandsgroesse mit eigener Gleichung, sondern genau "
    "der Lagrange-Multiplikator, der die Bedingung ∇·u = 0 erzwingt. "
    "Deshalb gibt es keine Druckgleichung zu integrieren, und deshalb "
    "muss die Poisson-Gleichung in **jedem** Zeitschritt neu geloest "
    "werden.\n\n"
    "**Und deshalb ist sie der teuerste Teil.** Der Transportschritt ist "
    "lokal: Jede Zelle schaut ihre Nachbarn an. Die Poisson-Gleichung ist "
    "global — eine Quelle in einer Ecke aendert den Druck im ganzen "
    "Gebiet, sofort. Das ist kein Mangel des Verfahrens, sondern die "
    "Physik der Inkompressibilitaet: Schall hat unendliche "
    "Geschwindigkeit, wenn man ihn wegdefiniert hat.",

}
